/*
 * data_model_snapshot.c
 * 
 * Snapshot of code generation data model.
 * This information is included in the executable file
 * and does not affect any memory content in the embedded device.
 */
 
__attribute__((section("diagnostics_cinfo, info"), keep)) char MCAF_data_model_snapshot[] =
  "{\"motor\": {\"Tfr\": 0.006072,\"B\": 1.1095029e-05,\"Lq\": 0.000474,\"poleCount"
  "\": 4,\"rated_current\": 2.2,\"J\": 3.859584e-06,\"velocity\": {\"nominal\": 418"
  ".8790205,\"maximum\": 837.758040957,\"units\": \"rad\\/s\"},\"L\": 0.0003905,\"R"
  "\": 0.56924,\"current\": {\"maximum\": {\"continuous\": 2.2,\"peak\": 2.2},\"uni"
  "ts\": \"A\"},\"Ld\": 0.000307,\"Ke\": 0.0283624644552,\"id\": \"linix-45ZWN24-40"
  "\"},\"controller\": {\"encoder\": {\"tracking_loop\": {\"zeta\": 1.5}},\"foc\": "
  "{\"feedback\": {\"voltage_delay\": 0}},\"pll\": {\"delay_match\": true,\"propert"
  "ies\": {\"reference\": false},\"keInverseScaling\": 1.0},\"operation\": {\"min_d"
  "eceleration_time\": null},\"dyn_current\": {\"maxgain\": 1.1},\"zsmt\": {\"error"
  "Limit\": 0.99997,\"properties\": {\"independent\": true,\"reference\": false},\""
  "duration\": {\"lockDelay\": 0.05},\"probe\": {\"accumGain\": 1.0}},\"fault_detec"
  "t\": {\"recovery\": {\"attempts\": 3}}},\"metadata\": {\"MCC\": {\"architecture"
  "\": \"melody\",\"peripherals\": {\"instances\": [{\"name\": \"ADC1\",\"type\": "
  "\"adc\"},{\"name\": \"PWM\",\"type\": \"pwm_hs\"},{\"name\": \"QEI1\",\"type\": "
  "\"qei\"},{\"name\": \"TMR1\",\"type\": \"timer\"},{\"name\": \"SCCP1\",\"type\":"
  " \"timer\"},{\"name\": \"UART1\",\"type\": \"uart\"},{\"name\": \"OPA1\",\"type"
  "\": \"opa\"},{\"name\": \"OPA2\",\"type\": \"opa\"},{\"name\": \"OPA3\",\"type\""
  ": \"opa\"},{\"name\": \"CMP1\",\"type\": \"cmp\"}]},\"version\": \"5.7.1\",\"per"
  "ipheral_library\": {\"name\": \"melody\",\"version\": \"NA\"}},\"data_model\": {"
  "\"schema_version\": 5},\"motorBench\": {\"commit_id\": \"cca205f0cfd3911d9402cd4"
  "a9bb65183b7cd48b6\",\"version\": \"2.50.0\"},\"MCAF\": {\"build\": {\"commit_id"
  "\": \"128946\",\"date_str\": \"2025 Apr 09\",\"hostname\": \"motor-control-mcaf-"
  "tags-builder-r8-2frc38-1-0700f-4pfpx-1fklf\",\"time\": 1744217130.6,\"time_iso\""
  ": \"2025-04-09T16:45:30.604389\",\"time_str\": \"2025 Apr 09 16:45\",\"type\": "
  "\"release\",\"username\": \"jenkins\",\"version\": \"R8\\/RC38\"},\"build_time\""
  ": 1744217130.6,\"build_time_iso\": \"2025-04-09T16:45:30.604389\",\"build_time_s"
  "tr\": \"2025 Apr 09 16:45\",\"commit_id\": \"128946\",\"version\": \"R8\\/RC38\""
  "}},\"scdata\": {\"setup\": {\"communications\": {\"baudrate\": 625000},\"analysi"
  "s\": {\"spindown_time\": {\"units\": \"s\",\"value\": 1.0},\"max_motor_speed\": "
  "{\"units\": \"rad\\/s mechanical\",\"value\": 2094.4}},\"calibration\": {\"vdc\""
  ": {\"units\": \"V\",\"value\": 24.0},\"resistor\": {\"units\": \"ohms\",\"value"
  "\": 12.0}}}},\"autotune_result\": {\"current\": {\"Kp\": 0.614426781524,\"phase_"
  "margin\": 80.0,\"wc\": 2067.89631273,\"Ki\": 1270.57087596,\"pi_phase_lag\": 45."
  "0},\"velocity\": {\"Kp\": 0.00174257670995,\"phase_margin\": 65.0,\"wc\": 14.431"
  "9028651,\"Ki\": 0.00443439395413,\"pi_phase_lag\": 10.0}},\"code_generation_tag_"
  "map\": {\"application\": \"sample\",\"diagnostics\": \"x2cscope\"},\"operating_r"
  "ange\": {\"velocity\": {\"units_qualifier\": \"mechanical\",\"units\": \"rad\\/s"
  "\",\"minimum\": 261.7995}},\"build\": {\"hardware_spec\": \"mclv2:33ck256mp508_e"
  "xtopamp_pim\",\"normfactor_associations\": [{\"context\": null,\"annotations\": "
  "[{\"typerefs\": [\"MCAF_U_CURRENT_ABC\",\"MCAF_U_CURRENT_ALPHABETA\",\"MCAF_U_CU"
  "RRENT_DQ\",\"MCAF_U_CURRENT\",\"MCAF_MOTOR_DATA.omegaCtrl.outMin\",\"MCAF_MOTOR_"
  "DATA.omegaCtrl.outMax\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR"
  "_DATA.omegaCtrl.integrator\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_"
  "U_VOLTAGE_ABC\",\"MCAF_U_VOLTAGE_ALPHABETA\",\"MCAF_U_VOLTAGE_DQ\",\"MCAF_U_VOLT"
  "AGE\",\"MCAF_MOTOR_DATA.idCtrl.outMin\",\"MCAF_MOTOR_DATA.idCtrl.outMax\",\"MCAF"
  "_MOTOR_DATA.iqCtrl.outMin\",\"MCAF_MOTOR_DATA.iqCtrl.outMax\"],\"unit\": \"V\","
  "\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR_DATA.idCtrl.integrator\",\"MCAF_MOTOR_DA"
  "TA.iqCtrl.integrator\"],\"unit\": \"V\",\"q\": 31},{\"typerefs\": [\"MCAF_U_DUTY"
  "CYCLE_ABC\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_ELEC\"],\"uni"
  "t\": \"theta_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_MECH\"],\"unit\": \"t"
  "heta_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_MECH\"],\"unit\": \"omega_"
  "m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_ELEC\"],\"unit\": \"omega_e\","
  "\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_DTHETA_ELEC_DT\"],\"unit\": \"dthet"
  "a_elec_dt\",\"q\": 15},{\"typerefs\": [\"MCAF_U_TEMPERATURE\"],\"unit\": \"Tempe"
  "rature\",\"q\": 15},{\"typerefs\": [\"MCAF_U_DIMENSIONLESS\",\"MCAF_U_DIMENSIONL"
  "ESS_SINCOS\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_NORMALIZED_GAIN\"]"
  ",\"unit\": 1,\"q\": 14}]}]},\"drive\": {\"iout\": {\"measurement\": {\"compensat"
  "ion\": {\"channels\": [\"a\",\"b\"],\"values\": {\"a\": [1.0,0.0],\"b\": [0.0,1."
  "0]},\"offset\": {\"range\": 0.03125,\"samples\": 128,\"filterGain\": 0.25}}},\"t"
  "ime_constant\": 1.84e-07,\"fullscale\": 21.8,\"maximum\": {\"continuous\": 14.1}"
  ",\"units\": \"A\"},\"estimator\": {\"type\": \"pll\",\"runtimeSelect\": false,\""
  "atpll\": {\"tau1\": 0.0001,\"tau2\": 0.00219,\"kpfactor\": 1.9,\"kifactor\": 30}"
  ",\"smo\": {\"ke_low_limit\": 0.01},\"omega1\": 732.0,\"tau\": 0.00219},\"flux_co"
  "ntrol\": {\"emag_tau\": 0.001638,\"idref_tau\": 0.006552},\"temperature\": {\"fu"
  "llscale\": 327.68,\"units\": \"C\"},\"pwm\": {\"adc_sampling_delay\": 0,\"period"
  "\": 5e-05,\"duty_cycle\": {\"maximum\": 0.975,\"minimum\": 0.009},\"deadtime\": "
  "2e-06},\"mcaf\": {\"adc\": {\"triggerSettings\": {\"noTrigger\": \"NO_TRIGGER\","
  "\"trigger1\": \"PWM1_TRIGGER1\",\"trigger2\": \"PWM1_TRIGGER2\"},\"channels\": {"
  "\"prefix\": \"MCAF_ADC_\",\"critical\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\","
  "\"PHASEC_CURRENT\",\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"required\": {\"singl"
  "e_channel\": [\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\",\"POTENTIOMETER\"],\"dual_ch"
  "annel\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"DCLINK_VOLTAGE\",\"POTENTIOMET"
  "ER\"],\"triple_channel\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"PHASEC_CURREN"
  "T\",\"DCLINK_VOLTAGE\",\"POTENTIOMETER\"]},\"optional\": [\"PHASEA_VOLTAGE\",\"P"
  "HASEB_VOLTAGE\",\"PHASEC_VOLTAGE\",\"BRIDGE_TEMPERATURE\",\"ABSREF_VOLTAGE\"],\""
  "fullList\": [{\"name\": \"PHASEA_CURRENT\",\"c_fragment\": \"PhaseACurrent\",\"d"
  "escription\": \"phase A current\",\"type\": \"current\"},{\"name\": \"PHASEB_CUR"
  "RENT\",\"c_fragment\": \"PhaseBCurrent\",\"description\": \"phase B current\",\""
  "type\": \"current\"},{\"name\": \"PHASEC_CURRENT\",\"c_fragment\": \"PhaseCCurre"
  "nt\",\"description\": \"phase C current\",\"type\": \"current\"},{\"name\": \"PH"
  "ASEA_VOLTAGE\",\"c_fragment\": \"PhaseAVoltage\",\"description\": \"phase A volt"
  "age\",\"type\": \"voltage\"},{\"name\": \"PHASEB_VOLTAGE\",\"c_fragment\": \"Pha"
  "seBVoltage\",\"description\": \"phase B voltage\",\"type\": \"voltage\"},{\"name"
  "\": \"PHASEC_VOLTAGE\",\"c_fragment\": \"PhaseCVoltage\",\"description\": \"phas"
  "e C voltage\",\"type\": \"voltage\"},{\"name\": \"DCLINK_CURRENT\",\"c_fragment"
  "\": \"DCLinkCurrent\",\"description\": \"DC link current\",\"type\": \"current\""
  "},{\"name\": \"DCLINK_VOLTAGE\",\"c_fragment\": \"DCLinkVoltage\",\"description"
  "\": \"DC link voltage\",\"type\": \"voltage\"},{\"name\": \"POTENTIOMETER\",\"c_"
  "fragment\": \"Potentiometer\",\"description\": \"potentiometer voltage\",\"type"
  "\": \"voltage\"},{\"name\": \"BRIDGE_TEMPERATURE\",\"c_fragment\": \"BridgeTempe"
  "rature\",\"description\": \"bridge temperature voltage\",\"type\": \"voltage\"},"
  "{\"name\": \"ABSREF_VOLTAGE\",\"c_fragment\": \"AbsoluteReferenceVoltage\",\"des"
  "cription\": \"absolute reference voltage\",\"type\": \"voltage\"}]}}},\"metadata"
  "\": {\"name\": \"dsPIC33CK LVMC\",\"id\": \"lvmc-33ck\"},\"vdc\": {\"nominal\": "
  "24.0,\"time_constant\": 0.0003147,\"fullscale\": 71.3,\"maximum\": 26.0,\"units"
  "\": \"V\",\"minimum\": 14.0},\"configuration\": {\"characteristics\": {\"current"
  "\": {\"dcLink\": {\"fullscale\": 21.8,\"timeConstant\": 1.84e-07},\"phase\": {\""
  "fullscale\": 21.8,\"maximum\": {\"continuous\": 14.1},\"timeConstant\": 1.84e-07"
  "}},\"device\": \"dsPIC33CK256MP508\",\"pwm\": {\"deadTime\": {\"default\": 1e-06"
  ",\"maximum\": 6e-06,\"minimum\": 6.7e-07},\"dutyCycle\": {\"maximum\": 0.975,\"m"
  "inimum\": 0.009},\"frequency\": {\"default\": 20000,\"maximum\": 100000,\"minimu"
  "m\": 1000}},\"voltage\": {\"dcLink\": {\"default\": 24.0,\"fullscale\": 71.3,\"m"
  "aximum\": 26.0,\"minimum\": 14.0,\"timeConstant\": 0.0003147},\"phase\": {\"full"
  "scale\": 71.3,\"timeConstant\": 0.0003147}}},\"identification\": {\"description"
  "\": \"dsPIC33CK Low Voltage Motor Control (LVMC) Development Board\",\"displayNa"
  "me\": \"dsPIC33CK LVMC\",\"id\": \"lvmc-33ck\"},\"peripherals\": {\"adc\": {\"cu"
  "rrent\": {\"a\": {\"channel\": \"AN0\",\"inverted\": true,\"signed\": true},\"b"
  "\": {\"channel\": \"AN1\",\"inverted\": true,\"signed\": true},\"c\": {\"channel"
  "\": \"AN10\",\"inverted\": true,\"signed\": true},\"dcLink\": {\"channel\": \"AN"
  "4\",\"inverted\": false,\"signed\": true}},\"other\": {\"bridgeTemperature\": {"
  "\"channel\": \"AN12\",\"gain\": 0.50354,\"offset\": 0.5,\"signed\": false},\"pot"
  "entiometer\": {\"channel\": \"AN11\",\"signed\": true}},\"samplingTime\": {\"def"
  "ault\": 3e-07,\"maximum\": 3e-07,\"minimum\": 3e-07},\"voltage\": {\"a\": {\"cha"
  "nnel\": \"AN17\",\"signed\": false},\"b\": {\"channel\": \"AN23\",\"signed\": fa"
  "lse},\"c\": {\"channel\": \"AN22\",\"signed\": false},\"dcLink\": {\"channel\": "
  "\"AN15\",\"signed\": true}}},\"comparator\": {\"inverted\": false,\"source\": \""
  "CMP1C\",\"threshold\": 0.95},\"debugger\": {\"channel\": 3},\"gpio\": {\"MCAF_BU"
  "TTON1\": {\"direction\": \"input\",\"pin\": \"RE11\",\"polarity\": \"active-high"
  "\"},\"MCAF_BUTTON2\": {\"direction\": \"input\",\"pin\": \"RE12\",\"polarity\": "
  "\"active-high\"},\"MCAF_LED1\": {\"direction\": \"output\",\"pin\": \"RE6\",\"po"
  "larity\": \"active-high\"},\"MCAF_LED2\": {\"direction\": \"output\",\"pin\": \""
  "RE7\",\"polarity\": \"active-high\"},\"MCAF_TESTPOINT1\": {\"direction\": \"outp"
  "ut\",\"pin\": \"RE4\",\"polarity\": \"active-high\"}},\"opamp\": {\"enabled\": ["
  "1,2,3]},\"oscillator\": {\"clockSource\": \"internal FRC\",\"inputClockFrequency"
  "\": 8000000},\"pwm\": {\"fault\": {\"polarity\": \"active-high\",\"source\": \"C"
  "MP1\"},\"generators\": {\"a\": 1,\"b\": 2,\"c\": 4},\"polarity\": {\"lower\": \""
  "active-high\",\"upper\": \"active-high\"}},\"qei\": {\"pins\": {\"A\": \"RC12\","
  "\"B\": \"RC13\",\"Z\": \"RC14\"}},\"uart\": {\"pins\": {\"RX\": \"RD14\",\"TX\":"
  " \"RD13\"}}}},\"idc\": {\"units\": \"A\"},\"sampling_time\": {\"current\": 5e-05"
  ",\"velocity\": 0.001},\"processor\": {\"clock_frequency\": 100000000.0,\"device"
  "\": \"dsPIC33CK256MP508\"}},\"config\": {\"ui\": {\"content\": {\"current_measur"
  "e-method\": \"triple_channel\",\"current_measure-single_channel-minimumTime\": 2"
  ".0,\"current_measure-single_channel-sampleDelay\": 0.0,\"current_measure-opamp-f"
  "ull_input_range\": true,\"estimator-type\": \"zsmt\",\"estimator-active-pll\": t"
  "rue,\"estimator-active-qei\": false,\"estimator-active-smo\": false,\"estimator-"
  "active-atpll\": false,\"estimator-active-zsmt\": false,\"estimator-active-ideal"
  "\": false,\"operation-min_velocity_ratio\": 0.25,\"operation-startup_velocity_ra"
  "tio\": 0.2744,\"operation-max_velocity_ratio\": 1.25,\"operation-fullscale_base_"
  "ratio\": 1.5,\"operation-outer_loop_type\": \"velocity\",\"operation-saliency-th"
  "reshold\": 1.25,\"operation-slewrate-accel\": 0.5,\"operation-slewrate-decel\": "
  "1.0,\"operation-dyn_current_type\": \"none\",\"operation-stopping-type\": \"mini"
  "mal_impact\",\"operation-stopping-closed_loop_parameters-speed\": 0.05,\"operati"
  "on-stopping-closed_loop_parameters-time\": 0.5,\"operation-stopping-coastdown-en"
  "d_velocity\": 0.05,\"operation-stopping-coastdown-time\": 1.2,\"fault_inject-get"
  "_tf-div0\": false,\"fault_inject-get_tf-missing_data\": false,\"fault_inject-get"
  "_tf-raise_value_error\": false,\"fault_inject-get_tf-raise_custom_error\": false"
  ",\"fault_inject-tf-tf_null\": false,\"fault_inject-tf-tf_jy\": false,\"fault_inj"
  "ect-tf-tf_jyex\": false,\"fault_inject-tf-div0\": false,\"fault_inject-tf-tau\":"
  " 0.0,\"flux_control-method\": \"none\",\"flux_control-eqn_based-ilimit-region_ty"
  "pe\": \"quadratic\",\"flux_control-eqn_based-ilimit-id_limit\": 0.7,\"flux_contr"
  "ol-eqn_based-ilimit-iq_limit\": 0.95,\"flux_control-eqn_based-fluxweak_enable\":"
  " false,\"flux_control-eqn_based-fw-vdq_limit\": 0.95,\"flux_control-eqn_based-mt"
  "pa_enable\": false,\"deadtimecomp-method\": \"none\",\"deadtimecomp-perphase-cur"
  "rent_sign_band\": 0.02,\"deadtimecomp-perphase-forward_gain\": 0.0,\"deadtimecom"
  "p-perphase-feedback_gain\": 0.0,\"fault_detect-margin_uv\": 2.0,\"fault_detect-m"
  "argin_ov\": 2.0,\"fault_detect-stall_detect_enable\": false,\"startup-Istartup\""
  ": 0.75,\"startup-t_rampup\": 25.0,\"startup-t_align\": 0.0,\"startup-min_total_a"
  "ccel_time\": 250.0,\"startup-torque_scale_accel\": 0.15,\"startup-torque_scale_s"
  "low_accel\": 0.2,\"startup-t_hold\": 0.0,\"startup-omega0\": 0.2,\"startup-theta"
  "_converge_rate\": 1.0,\"startup-method\": \"zsmt_dsat\",\"startup-damping-Imax\""
  ": 0.1,\"startup-damping-gainmax\": 40.0,\"startup-damping-omega_min\": 0.4,\"ove"
  "rmodulation-vd_limit\": 1.0,\"overmodulation-vq_limit\": 1.15,\"overmodulation-i"
  "nclude_duty_clipping\": true,\"pll-tau\": 2.19,\"pll-omega1\": 116.5,\"pll-veloc"
  "ity_filter_threshold\": 1.0,\"encoder-lines\": 250.0,\"encoder-index_present\": "
  "false,\"encoder-tracking_loop-tau\": 1.5,\"encoder-qei_sync-method\": \"align\","
  "\"encoder-qei_sync-align-t_align\": 0.5,\"encoder-qei_sync-align-angle_shift\": "
  "30.0,\"encoder-qei_sync-align-angle_init\": -30.0,\"encoder-qei_sync-align_sweep"
  "-sweep_rate_pow\": 1.0,\"encoder-qei_sync-align_sweep-setup_angle\": 45.0,\"enco"
  "der-qei_sync-pullout-pullout_slip\": 0.117,\"zsmt-excitation-kV\": 0.12,\"zsmt-e"
  "xcitation-kI\": 0.1,\"zsmt-pll-zeta\": 1.5,\"zsmt-pll-tau\": 10.0,\"zsmt-pll-tau"
  "_lpf\": 0.0,\"zsmt-pll-execution_divider\": 2.0,\"zsmt-startup-align_delay\": 1."
  "0,\"zsmt-startup-pll_lock_time\": 1.0,\"zsmt-startup-speed_limit\": 0.015,\"zsmt"
  "-startup-current_limit\": 0.3,\"zsmt-startup-probe_current\": 0.3,\"zsmt-startup"
  "-probe_duration\": 10.0,\"zsmt-startup-probe_slew_time\": 1.5,\"zsmt-startup-pro"
  "be_blanking_time\": 4.0,\"zsmt-hybrid-type\": \"minotaur\",\"zsmt-minotaur-volta"
  "ge_limit-vd\": 0.45,\"zsmt-minotaur-voltage_limit-vq\": 0.78,\"zsmt-minotaur-con"
  "verge-angle\": 10.0,\"zsmt-minotaur-converge-duration\": 2.0,\"zsmt-minotaur-vel"
  "ocity_threshold-slow\": 0.15,\"zsmt-minotaur-velocity_threshold-transition\": 0."
  "2,\"zsmt-minotaur-velocity_threshold-fast\": 0.25,\"zsmt-angle_correction-curren"
  "t_gain\": 0.0,\"dyn_current1-peak_factor\": 1.0,\"dyn_current1-horizon_factor\":"
  " 1.05,\"dyn_current1-tau\": 5.0,\"dyn_current1-nsamples\": 128.0,\"voltage_outer"
  "loop-tau_lpf\": 2.0,\"voltage_outerloop-Kp\": 0.1,\"voltage_outerloop-tau\": 100"
  ".0,\"mcapi-isSquaredTau\": 1.0,\"mcapi-iqTau\": 1.0,\"mcapi-adcIsrUserFunctions_"
  "enable\": false,\"board_service-uiServiceTiming\": 1.0,\"board_service-uiButtonD"
  "ebounceTime\": 7.0,\"board_service-uiButtonLongPressTime\": 2.5,\"test_harness-p"
  "erturbation_asymmetric\": false,\"adc-vtempbridge\": false,\"adc-temp_bridge_par"
  "ams-threshold\": 50.0,\"adc-temp_bridge_params-tau_lpf\": 10.0,\"adc-temp_bridge"
  "_params-slewrate\": 4.0,\"adc-vabsref\": false,\"adc-vphasea\": false,\"adc-vpha"
  "seb\": false,\"adc-vphasec\": false,\"diagnostics-method\": \"x2cscope\"},\"vers"
  "ion\": {\"schema\": 5.0,\"motorBench\": \"2.50.0\",\"MCAF\": \"R8\"},\"status\":"
  " {\"valid\": true}}}}";