/*
 * data_model_snapshot.c
 * 
 * Snapshot of code generation data model.
 * This information is included in the executable file
 * and does not affect any memory content in the embedded device.
 */
 
__attribute__((section("diagnostics_cinfo, info"), keep)) char MCAF_data_model_snapshot[] =
  "{\"motor\": {\"Tfr\": 0.006072,\"B\": 1.1095029e-05,\"Lq\": 0.000474,\"poleCount"
  "\": 4,\"rated_current\": 2.2,\"J\": 3.859584e-06,\"velocity\": {\"nominal\": 418"
  ".8790205,\"maximum\": 837.758040957,\"units\": \"rad\\/s\"},\"L\": 0.0003905,\"R"
  "\": 0.56924,\"current\": {\"maximum\": {\"continuous\": 2.2,\"peak\": 2.2},\"uni"
  "ts\": \"A\"},\"Ld\": 0.000307,\"Ke\": 0.0283624644552,\"id\": \"linix-45ZWN24-40"
  "\"},\"controller\": {\"encoder\": {\"tracking_loop\": {\"zeta\": 1.5}},\"foc\": "
  "{\"feedback\": {\"voltage_delay\": 0}},\"pll\": {\"delay_match\": true,\"propert"
  "ies\": {\"reference\": false},\"keInverseScaling\": 1.0},\"operation\": {\"min_d"
  "eceleration_time\": null},\"dyn_current\": {\"maxgain\": 1.1},\"zsmt\": {\"error"
  "Limit\": 0.99997,\"properties\": {\"independent\": true,\"reference\": false},\""
  "duration\": {\"lockDelay\": 0.05},\"probe\": {\"accumGain\": 1.0}},\"fault_detec"
  "t\": {\"recovery\": {\"attempts\": 3}}},\"metadata\": {\"MCC\": {\"architecture"
  "\": \"melody\",\"peripherals\": {\"instances\": [{\"name\": \"ADC1\",\"type\": "
  "\"adc\"},{\"name\": \"PWM\",\"type\": \"pwm_hs\"},{\"name\": \"QEI1\",\"type\": "
  "\"qei\"},{\"name\": \"SCCP1\",\"type\": \"timer\"},{\"name\": \"TMR1\",\"type\":"
  " \"timer\"},{\"name\": \"UART1\",\"type\": \"uart\"},{\"name\": \"OPA1\",\"type"
  "\": \"opa\"},{\"name\": \"OPA2\",\"type\": \"opa\"},{\"name\": \"OPA3\",\"type\""
  ": \"opa\"},{\"name\": \"CMP1\",\"type\": \"cmp\"}]},\"version\": \"5.9.0\",\"per"
  "ipheral_library\": {\"name\": \"melody\",\"version\": \"NA\"}},\"data_model\": {"
  "\"schema_version\": 5},\"motorBench\": {\"commit_id\": \"1940488a3e32dbadf4a6a2b"
  "f3f1f04b563e2dc2f\",\"version\": \"2.56.0\"},\"MCAF\": {\"build\": {\"commit_id"
  "\": \"132904\",\"date_str\": \"2026 Jul 14\",\"hostname\": \"motor-control-mcaf-"
  "tags-builder-r9-2frc32-1-pgvf1-2b576-j25lx\",\"time\": 1784005934.62,\"time_iso"
  "\": \"2026-07-14T05:12:14.622411\",\"time_str\": \"2026 Jul 14 05:12\",\"type\":"
  " \"release\",\"username\": \"jenkins\",\"version\": \"R9\\/RC32\"},\"build_time"
  "\": 1784005934.62,\"build_time_iso\": \"2026-07-14T05:12:14.622411\",\"build_tim"
  "e_str\": \"2026 Jul 14 05:12\",\"commit_id\": \"132904\",\"version\": \"R9\\/RC3"
  "2\"}},\"scdata\": {\"setup\": {\"communications\": {\"baudrate\": 625000},\"anal"
  "ysis\": {\"spindown_time\": {\"units\": \"s\",\"value\": 1.0},\"max_motor_speed"
  "\": {\"units\": \"rad\\/s mechanical\",\"value\": 2094.4}},\"calibration\": {\"v"
  "dc\": {\"units\": \"V\",\"value\": 24.0},\"resistor\": {\"units\": \"ohms\",\"va"
  "lue\": 12.0}}}},\"autotune_result\": {\"current\": {\"Kp\": 0.614426781524,\"pha"
  "se_margin\": 80.0,\"wc\": 2067.89631273,\"Ki\": 1270.57087596,\"pi_phase_lag\": "
  "45.0},\"velocity\": {\"Kp\": 0.00174257670995,\"phase_margin\": 65.0,\"wc\": 14."
  "4319028651,\"Ki\": 0.00443439395413,\"pi_phase_lag\": 10.0}},\"code_generation_t"
  "ag_map\": {\"application\": \"sample\",\"diagnostics\": \"x2cscope\"},\"operatin"
  "g_range\": {\"velocity\": {\"units_qualifier\": \"mechanical\",\"units\": \"rad"
  "\\/s\",\"minimum\": 261.7995}},\"build\": {\"hardware_spec\": \"mclv2:33ck256mp5"
  "08_extopamp_pim\",\"normfactor_associations\": [{\"context\": null,\"annotations"
  "\": [{\"typerefs\": [\"MCAF_U_CURRENT_ABC\",\"MCAF_U_CURRENT_ALPHABETA\",\"MCAF_"
  "U_CURRENT_DQ\",\"MCAF_U_CURRENT\",\"MCAF_MOTOR_DATA.omegaCtrl.outMin\",\"MCAF_MO"
  "TOR_DATA.omegaCtrl.outMax\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_M"
  "OTOR_DATA.omegaCtrl.integrator\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"M"
  "CAF_U_VOLTAGE_ABC\",\"MCAF_U_VOLTAGE_ALPHABETA\",\"MCAF_U_VOLTAGE_DQ\",\"MCAF_U_"
  "VOLTAGE\",\"MCAF_MOTOR_DATA.idCtrl.outMin\",\"MCAF_MOTOR_DATA.idCtrl.outMax\",\""
  "MCAF_MOTOR_DATA.iqCtrl.outMin\",\"MCAF_MOTOR_DATA.iqCtrl.outMax\"],\"unit\": \"V"
  "\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR_DATA.idCtrl.integrator\",\"MCAF_MOTOR"
  "_DATA.iqCtrl.integrator\"],\"unit\": \"V\",\"q\": 31},{\"typerefs\": [\"MCAF_U_D"
  "UTYCYCLE_ABC\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_ELEC\"],\""
  "unit\": \"theta_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_MECH\"],\"unit\": "
  "\"theta_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_MECH\"],\"unit\": \"ome"
  "ga_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_ELEC\"],\"unit\": \"omega_e"
  "\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_DTHETA_ELEC_DT\"],\"unit\": \"dt"
  "heta_elec_dt\",\"q\": 15},{\"typerefs\": [\"MCAF_U_TEMPERATURE\"],\"unit\": \"Te"
  "mperature\",\"q\": 15},{\"typerefs\": [\"MCAF_U_DIMENSIONLESS\",\"MCAF_U_DIMENSI"
  "ONLESS_SINCOS\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_NORMALIZED_GAIN"
  "\"],\"unit\": 1,\"q\": 14},{\"typerefs\": [\"MCAF_U_NORMALIZED_Q15\"],\"unit\": "
  "1,\"q\": 15}]}]},\"drive\": {\"iout\": {\"measurement\": {\"compensation\": {\"c"
  "hannels\": [\"a\",\"b\"],\"values\": {\"a\": [1.0,0.0],\"b\": [0.0,1.0]},\"offse"
  "t\": {\"samples\": 128,\"filterGain\": 0.25},\"gain\": {\"samples\": 128}}},\"ti"
  "me_constant\": 1.84e-07,\"fullscale\": 21.8,\"maximum\": {\"continuous\": 14.1,"
  "\"peak\": 14.1},\"units\": \"A\"},\"estimator\": {\"type\": \"pll\",\"runtimeSel"
  "ect\": false,\"smo\": {\"ke_low_limit\": 0.01},\"omega1\": 732.0,\"tau\": 0.0021"
  "9},\"flux_control\": {\"emag_tau\": 0.001638,\"idref_tau\": 0.006552},\"temperat"
  "ure\": {\"fullscale\": 327.68,\"units\": \"C\"},\"pwm\": {\"adc_sampling_delay\""
  ": 0,\"period\": 5e-05,\"duty_cycle\": {\"maximum\": 0.975,\"minimum\": 0.009},\""
  "deadtime\": 1e-06},\"mcaf\": {\"adc\": {\"triggerSettings\": {\"noTrigger\": \"N"
  "O_TRIGGER\",\"trigger1\": \"PWM1_TRIGGER1\",\"trigger2\": \"PWM1_TRIGGER2\"},\"c"
  "hannels\": {\"prefix\": \"MCAF_ADC_\",\"critical\": [\"PHASEA_CURRENT\",\"PHASEB"
  "_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"required"
  "\": {\"single_channel\": [\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"dual_channel"
  "\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"DCLINK_VOLTAGE\"],\"triple_channel"
  "\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_VOLTAGE\""
  "]},\"optional\": [\"POTENTIOMETER\",\"PHASEA_VOLTAGE\",\"PHASEB_VOLTAGE\",\"PHAS"
  "EC_VOLTAGE\",\"BRIDGE_TEMPERATURE\",\"ABSREF_VOLTAGE\"],\"fullList\": [{\"name\""
  ": \"PHASEA_CURRENT\",\"c_fragment\": \"PhaseACurrent\",\"description\": \"phase "
  "A current\",\"type\": \"current\"},{\"name\": \"PHASEB_CURRENT\",\"c_fragment\":"
  " \"PhaseBCurrent\",\"description\": \"phase B current\",\"type\": \"current\"},{"
  "\"name\": \"PHASEC_CURRENT\",\"c_fragment\": \"PhaseCCurrent\",\"description\": "
  "\"phase C current\",\"type\": \"current\"},{\"name\": \"PHASEA_VOLTAGE\",\"c_fra"
  "gment\": \"PhaseAVoltage\",\"description\": \"phase A voltage\",\"type\": \"volt"
  "age\"},{\"name\": \"PHASEB_VOLTAGE\",\"c_fragment\": \"PhaseBVoltage\",\"descrip"
  "tion\": \"phase B voltage\",\"type\": \"voltage\"},{\"name\": \"PHASEC_VOLTAGE\""
  ",\"c_fragment\": \"PhaseCVoltage\",\"description\": \"phase C voltage\",\"type\""
  ": \"voltage\"},{\"name\": \"DCLINK_CURRENT\",\"c_fragment\": \"DCLinkCurrent\","
  "\"description\": \"DC link current\",\"type\": \"current\"},{\"name\": \"DCLINK_"
  "VOLTAGE\",\"c_fragment\": \"DCLinkVoltage\",\"description\": \"DC link voltage\""
  ",\"type\": \"voltage\"},{\"name\": \"POTENTIOMETER\",\"c_fragment\": \"Potentiom"
  "eter\",\"description\": \"potentiometer voltage\",\"type\": \"voltage\"},{\"name"
  "\": \"BRIDGE_TEMPERATURE\",\"c_fragment\": \"BridgeTemperature\",\"description\""
  ": \"bridge temperature voltage\",\"type\": \"voltage\"},{\"name\": \"ABSREF_VOLT"
  "AGE\",\"c_fragment\": \"AbsoluteReferenceVoltage\",\"description\": \"absolute r"
  "eference voltage\",\"type\": \"voltage\"}]}}},\"metadata\": {\"name\": \"dsPIC33"
  "CK LVMC\",\"id\": \"lvmc-33ck\"},\"vdc\": {\"time_constant\": 0.0003147,\"nomina"
  "l\": 24.0,\"fullscale\": 71.3,\"maximum\": 26.0,\"units\": \"V\",\"minimum\": 14"
  ".0},\"configuration\": {\"characteristics\": {\"current\": {\"dcLink\": {\"fulls"
  "cale\": 21.8,\"timeConstant\": 1.84e-07},\"phase\": {\"fullscale\": 21.8,\"maxim"
  "um\": {\"continuous\": 14.1},\"timeConstant\": 1.84e-07}},\"device\": \"dsPIC33C"
  "K256MP508\",\"pwm\": {\"deadTime\": {\"default\": 1e-06,\"maximum\": 6e-06,\"min"
  "imum\": 6.7e-07},\"dutyCycle\": {\"maximum\": 0.975,\"minimum\": 0.009},\"freque"
  "ncy\": {\"default\": 20000,\"maximum\": 100000,\"minimum\": 1000}},\"voltage\": "
  "{\"dcLink\": {\"default\": 24.0,\"fullscale\": 71.3,\"maximum\": 26.0,\"minimum"
  "\": 14.0,\"timeConstant\": 0.0003147},\"phase\": {\"fullscale\": 71.3,\"timeCons"
  "tant\": 0.0003147}}},\"identification\": {\"description\": \"dsPIC33CK Low Volta"
  "ge Motor Control (LVMC) Development Board\",\"displayName\": \"dsPIC33CK LVMC\","
  "\"id\": \"lvmc-33ck\"},\"peripherals\": {\"adc\": {\"current\": {\"a\": {\"chann"
  "el\": \"AN0\",\"inverted\": true,\"signed\": true},\"b\": {\"channel\": \"AN1\","
  "\"inverted\": true,\"signed\": true},\"c\": {\"channel\": \"AN10\",\"inverted\":"
  " true,\"signed\": true},\"dcLink\": {\"channel\": \"AN4\",\"inverted\": false,\""
  "signed\": true}},\"other\": {\"bridgeTemperature\": {\"channel\": \"AN12\",\"gai"
  "n\": 0.50354,\"offset\": 0.5,\"signed\": false},\"potentiometer\": {\"channel\":"
  " \"AN11\",\"signed\": true}},\"samplingTime\": {\"default\": 3e-07,\"maximum\": "
  "3e-07,\"minimum\": 3e-07},\"voltage\": {\"a\": {\"channel\": \"AN17\",\"signed\""
  ": false},\"b\": {\"channel\": \"AN23\",\"signed\": false},\"c\": {\"channel\": "
  "\"AN22\",\"signed\": false},\"dcLink\": {\"channel\": \"AN15\",\"signed\": true}"
  "}},\"comparator\": {\"inverted\": false,\"source\": \"CMP1C\",\"threshold\": 0.9"
  "5},\"debugger\": {\"channel\": 3},\"gpio\": {\"MCAF_BUTTON1\": {\"direction\": "
  "\"input\",\"pin\": \"RE11\",\"polarity\": \"active-high\"},\"MCAF_BUTTON2\": {\""
  "direction\": \"input\",\"pin\": \"RE12\",\"polarity\": \"active-high\"},\"MCAF_L"
  "ED1\": {\"direction\": \"output\",\"pin\": \"RE6\",\"polarity\": \"active-high\""
  "},\"MCAF_LED2\": {\"direction\": \"output\",\"pin\": \"RE7\",\"polarity\": \"act"
  "ive-high\"},\"MCAF_TESTPOINT1\": {\"direction\": \"output\",\"pin\": \"RE4\",\"p"
  "olarity\": \"active-high\"}},\"opamp\": {\"enabled\": [1,2,3]},\"oscillator\": {"
  "\"clockSource\": \"internal FRC\",\"inputClockFrequency\": 8000000},\"pwm\": {\""
  "fault\": {\"polarity\": \"active-high\",\"source\": \"CMP1\"},\"generators\": {"
  "\"a\": 1,\"b\": 2,\"c\": 4},\"polarity\": {\"lower\": \"active-high\",\"upper\":"
  " \"active-high\"}},\"qei\": {\"pins\": {\"A\": \"RC12\",\"B\": \"RC13\",\"Z\": "
  "\"RC14\"}},\"uart\": {\"pins\": {\"RX\": \"RD14\",\"TX\": \"RD13\"}}}},\"idc\": "
  "{\"units\": \"A\"},\"sampling_time\": {\"current\": 5e-05,\"velocity\": 0.001},"
  "\"processor\": {\"clock_frequency\": 100000000.0,\"device\": \"dsPIC33CK256MP508"
  "\"}},\"config\": {\"ui\": {\"content\": {\"current_measure-method\": \"triple_ch"
  "annel\",\"current_measure-single_channel-minimumTime\": 2.0,\"current_measure-si"
  "ngle_channel-sampleDelay\": 0.0,\"current_measure-opamp-full_input_range\": true"
  ",\"current_measure-offset_cal-range\": 0.04,\"estimator-type\": \"zsmt\",\"estim"
  "ator-active-pll\": true,\"estimator-active-smo\": false,\"estimator-active-qei\""
  ": false,\"estimator-active-atpll\": false,\"estimator-active-zsmt\": false,\"est"
  "imator-active-ideal\": false,\"operation-min_velocity_ratio\": 0.1,\"operation-s"
  "tartup_velocity_ratio\": 0.2744,\"operation-max_velocity_ratio\": 1.25,\"operati"
  "on-fullscale_base_ratio\": 1.5,\"operation-outer_loop_type\": \"velocity\",\"ope"
  "ration-saliency-threshold\": 1.25,\"operation-slewrate-accel\": 0.5,\"operation-"
  "slewrate-decel\": 1.0,\"operation-dyn_current_type\": \"none\",\"operation-stopp"
  "ing-type\": \"minimal_impact\",\"operation-stopping-closed_loop_parameters-speed"
  "\": 0.05,\"operation-stopping-closed_loop_parameters-time\": 0.5,\"operation-sto"
  "pping-coastdown-end_velocity\": 0.05,\"operation-stopping-coastdown-time\": 1.2,"
  "\"fault_inject-get_tf-div0\": false,\"fault_inject-get_tf-missing_data\": false,"
  "\"fault_inject-get_tf-raise_value_error\": false,\"fault_inject-get_tf-raise_cus"
  "tom_error\": false,\"fault_inject-tf-tf_null\": false,\"fault_inject-tf-tf_jy\":"
  " false,\"fault_inject-tf-tf_jyex\": false,\"fault_inject-tf-div0\": false,\"faul"
  "t_inject-tf-tau\": 0.0,\"flux_control-method\": \"none\",\"flux_control-eqn_base"
  "d-ilimit-region_type\": \"quadratic\",\"flux_control-eqn_based-ilimit-id_limit\""
  ": 0.7,\"flux_control-eqn_based-ilimit-iq_limit\": 0.95,\"flux_control-eqn_based-"
  "fluxweak_enable\": false,\"flux_control-eqn_based-fw-vdq_limit\": 0.95,\"flux_co"
  "ntrol-eqn_based-mtpa_enable\": false,\"deadtimecomp-method\": \"none\",\"deadtim"
  "ecomp-perphase-current_sign_band\": 0.02,\"deadtimecomp-perphase-forward_gain\":"
  " 0.0,\"deadtimecomp-perphase-feedback_gain\": 0.0,\"fault_detect-margin_uv\": 2."
  "0,\"fault_detect-margin_ov\": 2.0,\"fault_detect-stall_detect_enable\": false,\""
  "startup-Istartup\": 0.75,\"startup-t_rampup\": 25.0,\"startup-t_align\": 0.0,\"s"
  "tartup-min_total_accel_time\": 250.0,\"startup-torque_scale_accel\": 0.15,\"star"
  "tup-torque_scale_slow_accel\": 0.2,\"startup-t_hold\": 0.0,\"startup-omega0\": 0"
  ".2,\"startup-theta_converge_rate\": 1.0,\"startup-method\": \"zsmt_dsat\",\"star"
  "tup-damping-Imax\": 0.133,\"startup-damping-gainmax\": 40.0,\"startup-damping-om"
  "ega_min\": 0.4,\"overmodulation-vd_limit\": 1.0,\"overmodulation-vq_limit\": 1.1"
  "5,\"overmodulation-include_duty_clipping\": true,\"atpll-tau1\": 0.1,\"atpll-tau"
  "2\": 2.19,\"atpll-kp\": 1.9,\"atpll-ki\": 30.0,\"pll-tau\": 2.19,\"pll-omega1\":"
  " 116.5,\"pll-velocity_filter_threshold\": 1.0,\"smo-velocity_loop_cutoff\": 0.3,"
  "\"encoder-lines\": 250.0,\"encoder-index_present\": false,\"encoder-tracking_loo"
  "p-tau\": 1.5,\"encoder-qei_sync-method\": \"align\",\"encoder-qei_sync-align-t_a"
  "lign\": 0.5,\"encoder-qei_sync-align-angle_shift\": 30.0,\"encoder-qei_sync-alig"
  "n-angle_init\": -30.0,\"encoder-qei_sync-align_sweep-sweep_rate_pow\": 1.0,\"enc"
  "oder-qei_sync-align_sweep-setup_angle\": 45.0,\"encoder-qei_sync-pullout-pullout"
  "_slip\": 0.117,\"zsmt-excitation-kV\": 0.12,\"zsmt-excitation-kI\": 0.1,\"zsmt-p"
  "ll-zeta\": 1.5,\"zsmt-pll-tau\": 10.0,\"zsmt-pll-tau_lpf\": 0.0,\"zsmt-pll-execu"
  "tion_divider\": 2.0,\"zsmt-startup-align_delay\": 1.0,\"zsmt-startup-pll_lock_ti"
  "me\": 1.0,\"zsmt-startup-speed_limit\": 0.015,\"zsmt-startup-current_limit\": 0."
  "3,\"zsmt-startup-probe_current\": 0.8,\"zsmt-startup-probe_duration\": 10.0,\"zs"
  "mt-startup-probe_slew_time\": 1.5,\"zsmt-startup-probe_blanking_time\": 4.0,\"zs"
  "mt-hybrid-type\": \"minotaur\",\"zsmt-minotaur-voltage_limit-vd\": 0.45,\"zsmt-m"
  "inotaur-voltage_limit-vq\": 0.78,\"zsmt-minotaur-converge-angle\": 10.0,\"zsmt-m"
  "inotaur-converge-duration\": 2.0,\"zsmt-minotaur-velocity_threshold-slow\": 0.2,"
  "\"zsmt-minotaur-velocity_threshold-transition\": 0.25,\"zsmt-minotaur-velocity_t"
  "hreshold-fast\": 0.3,\"zsmt-angle_correction-current_gain\": 0.0,\"dyn_current1-"
  "peak_factor\": 1.0,\"dyn_current1-horizon_factor\": 1.05,\"dyn_current1-tau\": 5"
  ".0,\"dyn_current1-nsamples\": 128.0,\"voltage_outerloop-tau_lpf\": 2.0,\"voltage"
  "_outerloop-Kp\": 0.1,\"voltage_outerloop-tau\": 100.0,\"mcapi-isSquaredTau\": 1."
  "0,\"mcapi-iqTau\": 1.0,\"mcapi-adcIsrUserFunctions_enable\": false,\"board_servi"
  "ce-uiServiceTiming\": 1.0,\"board_service-uiButtonDebounceTime\": 7.0,\"board_se"
  "rvice-uiButtonLongPressTime\": 2.5,\"test_harness-perturbation_asymmetric\": fal"
  "se,\"test_harness-codegen-test_harness\": false,\"test_harness-codegen-test_prof"
  "iling\": false,\"adc-vtempbridge\": false,\"adc-temp_bridge_params-threshold\": "
  "50.0,\"adc-temp_bridge_params-tau_lpf\": 10.0,\"adc-temp_bridge_params-slewrate"
  "\": 4.0,\"adc-vabsref\": false,\"adc-vphasea\": false,\"adc-vphaseb\": false,\"a"
  "dc-vphasec\": false,\"diagnostics-method\": \"x2cscope\"},\"version\": {\"schema"
  "\": 6.0,\"motorBench\": \"2.55.0\",\"MCAF\": \"R9\"},\"status\": {\"valid\": tru"
  "e}}}}";