/*
 * data_model_snapshot.c
 * 
 * Snapshot of code generation data model.
 * This information is included in the executable file
 * and does not affect any memory content in the embedded device.
 */
 
__attribute__((section("diagnostics_cinfo, info"), keep)) char MCAF_data_model_snapshot[] =
  "{\"motor\": {\"Tfr\": 0.0281,\"B\": 1.90141e-05,\"Lq\": 0.0004853,\"poleCount\":"
  " 4,\"rated_current\": 7.5,\"J\": 5.55319e-05,\"velocity\": {\"nominal\": 314.159"
  "265359,\"maximum\": 628.318530718,\"units\": \"rad\\/s\"},\"L\": 0.0004162,\"R\""
  ": 0.1859,\"current\": {\"maximum\": {\"continuous\": 7.5,\"peak\": 7.5},\"units"
  "\": \"A\"},\"Ld\": 0.0003471,\"Ke\": 0.0314613077567,\"id\": \"elra-ipm80s-24v\""
  "},\"controller\": {\"encoder\": {\"tracking_loop\": {\"zeta\": 1.5}},\"foc\": {"
  "\"feedback\": {\"voltage_delay\": 0}},\"pll\": {\"delay_match\": true,\"properti"
  "es\": {\"reference\": false},\"keInverseScaling\": 1.0},\"operation\": {\"min_de"
  "celeration_time\": null},\"dyn_current\": {\"maxgain\": 1.1},\"zsmt\": {\"errorL"
  "imit\": 0.99997,\"properties\": {\"independent\": true,\"reference\": false},\"d"
  "uration\": {\"lockDelay\": 0.05},\"probe\": {\"accumGain\": 1.0}},\"fault_detect"
  "\": {\"recovery\": {\"attempts\": 3}}},\"metadata\": {\"MCC\": {\"architecture\""
  ": \"melody\",\"peripherals\": {\"instances\": [{\"name\": \"ADC1\",\"type\": \"a"
  "dc\"},{\"name\": \"PWM\",\"type\": \"pwm_hs\"},{\"name\": \"QEI1\",\"type\": \"q"
  "ei\"},{\"name\": \"SCCP1\",\"type\": \"timer\"},{\"name\": \"TMR1\",\"type\": \""
  "timer\"},{\"name\": \"UART1\",\"type\": \"uart\"},{\"name\": \"OPA1\",\"type\": "
  "\"opa\"},{\"name\": \"OPA2\",\"type\": \"opa\"},{\"name\": \"OPA3\",\"type\": \""
  "opa\"},{\"name\": \"CMP1\",\"type\": \"cmp\"}]},\"version\": \"5.8.4\",\"periphe"
  "ral_library\": {\"name\": \"melody\",\"version\": \"NA\"}},\"data_model\": {\"sc"
  "hema_version\": 5},\"motorBench\": {\"commit_id\": \"c114bdc6e8ebb44adc1b5cd1e6b"
  "92ea0b107647e\",\"version\": \"2.55.0\"},\"MCAF\": {\"build\": {\"commit_id\": "
  "\"132024\",\"date_str\": \"2026 Feb 13\",\"hostname\": \"motor-control-mcaf-tags"
  "-builder-r9-2frc31-1-4qzv8-0zfbw-3kggr\",\"time\": 1771007857.63,\"time_iso\": "
  "\"2026-02-13T18:37:37.630250\",\"time_str\": \"2026 Feb 13 18:37\",\"type\": \"r"
  "elease\",\"username\": \"jenkins\",\"version\": \"R9\\/RC31\"},\"build_time\": 1"
  "771007857.63,\"build_time_iso\": \"2026-02-13T18:37:37.630250\",\"build_time_str"
  "\": \"2026 Feb 13 18:37\",\"commit_id\": \"132024\",\"version\": \"R9\\/RC31\"}}"
  ",\"scdata\": {\"setup\": {\"communications\": {\"baudrate\": 625000},\"analysis"
  "\": {\"spindown_time\": {\"units\": \"s\",\"value\": 1.0},\"max_motor_speed\": {"
  "\"units\": \"rad\\/s mechanical\",\"value\": 2094.4}},\"calibration\": {\"vdc\":"
  " {\"units\": \"V\",\"value\": 24.0},\"resistor\": {\"units\": \"ohms\",\"value\""
  ": 12.0}}}},\"autotune_result\": {\"current\": {\"Kp\": 0.218574077269,\"phase_ma"
  "rgin\": 80.0,\"wc\": 686.86458694,\"Ki\": 150.130793299,\"pi_phase_lag\": 45.0},"
  "\"velocity\": {\"Kp\": 0.0135818369396,\"phase_margin\": 65.0,\"wc\": 9.63501965"
  "242,\"Ki\": 0.0230743718954,\"pi_phase_lag\": 10.0}},\"code_generation_tag_map\""
  ": {\"application\": \"sample\",\"diagnostics\": \"x2cscope\"},\"operating_range"
  "\": {\"velocity\": {\"units_qualifier\": \"mechanical\",\"units\": \"rad\\/s\","
  "\"minimum\": 261.7995}},\"build\": {\"hardware_spec\": \"mclv2:33ck256mp508_exto"
  "pamp_pim\",\"normfactor_associations\": [{\"context\": null,\"annotations\": [{"
  "\"typerefs\": [\"MCAF_U_CURRENT_ABC\",\"MCAF_U_CURRENT_ALPHABETA\",\"MCAF_U_CURR"
  "ENT_DQ\",\"MCAF_U_CURRENT\",\"MCAF_MOTOR_DATA.omegaCtrl.outMin\",\"MCAF_MOTOR_DA"
  "TA.omegaCtrl.outMax\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR_D"
  "ATA.omegaCtrl.integrator\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_U_"
  "VOLTAGE_ABC\",\"MCAF_U_VOLTAGE_ALPHABETA\",\"MCAF_U_VOLTAGE_DQ\",\"MCAF_U_VOLTAG"
  "E\",\"MCAF_MOTOR_DATA.idCtrl.outMin\",\"MCAF_MOTOR_DATA.idCtrl.outMax\",\"MCAF_M"
  "OTOR_DATA.iqCtrl.outMin\",\"MCAF_MOTOR_DATA.iqCtrl.outMax\"],\"unit\": \"V\",\"q"
  "\": 15},{\"typerefs\": [\"MCAF_MOTOR_DATA.idCtrl.integrator\",\"MCAF_MOTOR_DATA."
  "iqCtrl.integrator\"],\"unit\": \"V\",\"q\": 31},{\"typerefs\": [\"MCAF_U_DUTYCYC"
  "LE_ABC\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_ELEC\"],\"unit\""
  ": \"theta_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_MECH\"],\"unit\": \"thet"
  "a_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_MECH\"],\"unit\": \"omega_m\""
  ",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_ELEC\"],\"unit\": \"omega_e\",\"q"
  "\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_DTHETA_ELEC_DT\"],\"unit\": \"dtheta_e"
  "lec_dt\",\"q\": 15},{\"typerefs\": [\"MCAF_U_TEMPERATURE\"],\"unit\": \"Temperat"
  "ure\",\"q\": 15},{\"typerefs\": [\"MCAF_U_DIMENSIONLESS\",\"MCAF_U_DIMENSIONLESS"
  "_SINCOS\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_NORMALIZED_GAIN\"],\""
  "unit\": 1,\"q\": 14},{\"typerefs\": [\"MCAF_U_NORMALIZED_Q15\"],\"unit\": 1,\"q"
  "\": 15}]}]},\"drive\": {\"iout\": {\"measurement\": {\"compensation\": {\"channe"
  "ls\": [\"a\",\"b\"],\"values\": {\"a\": [1.0,0.0],\"b\": [0.0,1.0]},\"offset\": "
  "{\"samples\": 128,\"filterGain\": 0.25},\"gain\": {\"samples\": 128}}},\"time_co"
  "nstant\": 1.84e-07,\"fullscale\": 21.8,\"maximum\": {\"continuous\": 14.1,\"peak"
  "\": 14.1},\"units\": \"A\"},\"estimator\": {\"type\": \"pll\",\"runtimeSelect\":"
  " false,\"smo\": {\"ke_low_limit\": 0.01},\"omega1\": 732.0,\"tau\": 0.00219},\"f"
  "lux_control\": {\"emag_tau\": 0.001638,\"idref_tau\": 0.006552},\"temperature\":"
  " {\"fullscale\": 327.68,\"units\": \"C\"},\"pwm\": {\"adc_sampling_delay\": 0,\""
  "period\": 5e-05,\"duty_cycle\": {\"maximum\": 0.975,\"minimum\": 0.009},\"deadti"
  "me\": 1e-06},\"mcaf\": {\"adc\": {\"triggerSettings\": {\"noTrigger\": \"NO_TRIG"
  "GER\",\"trigger1\": \"PWM1_TRIGGER1\",\"trigger2\": \"PWM1_TRIGGER2\"},\"channel"
  "s\": {\"prefix\": \"MCAF_ADC_\",\"critical\": [\"PHASEA_CURRENT\",\"PHASEB_CURRE"
  "NT\",\"PHASEC_CURRENT\",\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"required\": {\""
  "single_channel\": [\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"dual_channel\": [\"P"
  "HASEA_CURRENT\",\"PHASEB_CURRENT\",\"DCLINK_VOLTAGE\"],\"triple_channel\": [\"PH"
  "ASEA_CURRENT\",\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_VOLTAGE\"]},\"opti"
  "onal\": [\"POTENTIOMETER\",\"PHASEA_VOLTAGE\",\"PHASEB_VOLTAGE\",\"PHASEC_VOLTAG"
  "E\",\"BRIDGE_TEMPERATURE\",\"ABSREF_VOLTAGE\"],\"fullList\": [{\"name\": \"PHASE"
  "A_CURRENT\",\"c_fragment\": \"PhaseACurrent\",\"description\": \"phase A current"
  "\",\"type\": \"current\"},{\"name\": \"PHASEB_CURRENT\",\"c_fragment\": \"PhaseB"
  "Current\",\"description\": \"phase B current\",\"type\": \"current\"},{\"name\":"
  " \"PHASEC_CURRENT\",\"c_fragment\": \"PhaseCCurrent\",\"description\": \"phase C"
  " current\",\"type\": \"current\"},{\"name\": \"PHASEA_VOLTAGE\",\"c_fragment\": "
  "\"PhaseAVoltage\",\"description\": \"phase A voltage\",\"type\": \"voltage\"},{"
  "\"name\": \"PHASEB_VOLTAGE\",\"c_fragment\": \"PhaseBVoltage\",\"description\": "
  "\"phase B voltage\",\"type\": \"voltage\"},{\"name\": \"PHASEC_VOLTAGE\",\"c_fra"
  "gment\": \"PhaseCVoltage\",\"description\": \"phase C voltage\",\"type\": \"volt"
  "age\"},{\"name\": \"DCLINK_CURRENT\",\"c_fragment\": \"DCLinkCurrent\",\"descrip"
  "tion\": \"DC link current\",\"type\": \"current\"},{\"name\": \"DCLINK_VOLTAGE\""
  ",\"c_fragment\": \"DCLinkVoltage\",\"description\": \"DC link voltage\",\"type\""
  ": \"voltage\"},{\"name\": \"POTENTIOMETER\",\"c_fragment\": \"Potentiometer\",\""
  "description\": \"potentiometer voltage\",\"type\": \"voltage\"},{\"name\": \"BRI"
  "DGE_TEMPERATURE\",\"c_fragment\": \"BridgeTemperature\",\"description\": \"bridg"
  "e temperature voltage\",\"type\": \"voltage\"},{\"name\": \"ABSREF_VOLTAGE\",\"c"
  "_fragment\": \"AbsoluteReferenceVoltage\",\"description\": \"absolute reference "
  "voltage\",\"type\": \"voltage\"}]}}},\"metadata\": {\"name\": \"dsPIC33CK LVMC\""
  ",\"id\": \"lvmc-33ck\"},\"vdc\": {\"time_constant\": 0.0003147,\"nominal\": 24.0"
  ",\"fullscale\": 71.3,\"maximum\": 26.0,\"units\": \"V\",\"minimum\": 14.0},\"con"
  "figuration\": {\"characteristics\": {\"current\": {\"dcLink\": {\"fullscale\": 2"
  "1.8,\"timeConstant\": 1.84e-07},\"phase\": {\"fullscale\": 21.8,\"maximum\": {\""
  "continuous\": 14.1},\"timeConstant\": 1.84e-07}},\"device\": \"dsPIC33CK256MP508"
  "\",\"pwm\": {\"deadTime\": {\"default\": 1e-06,\"maximum\": 6e-06,\"minimum\": 6"
  ".7e-07},\"dutyCycle\": {\"maximum\": 0.975,\"minimum\": 0.009},\"frequency\": {"
  "\"default\": 20000,\"maximum\": 100000,\"minimum\": 1000}},\"voltage\": {\"dcLin"
  "k\": {\"default\": 24.0,\"fullscale\": 71.3,\"maximum\": 26.0,\"minimum\": 14.0,"
  "\"timeConstant\": 0.0003147},\"phase\": {\"fullscale\": 71.3,\"timeConstant\": 0"
  ".0003147}}},\"identification\": {\"description\": \"dsPIC33CK Low Voltage Motor "
  "Control (LVMC) Development Board\",\"displayName\": \"dsPIC33CK LVMC\",\"id\": "
  "\"lvmc-33ck\"},\"peripherals\": {\"adc\": {\"current\": {\"a\": {\"channel\": \""
  "AN0\",\"inverted\": true,\"signed\": true},\"b\": {\"channel\": \"AN1\",\"invert"
  "ed\": true,\"signed\": true},\"c\": {\"channel\": \"AN10\",\"inverted\": true,\""
  "signed\": true},\"dcLink\": {\"channel\": \"AN4\",\"inverted\": false,\"signed\""
  ": true}},\"other\": {\"bridgeTemperature\": {\"channel\": \"AN12\",\"gain\": 0.5"
  "0354,\"offset\": 0.5,\"signed\": false},\"potentiometer\": {\"channel\": \"AN11"
  "\",\"signed\": true}},\"samplingTime\": {\"default\": 3e-07,\"maximum\": 3e-07,"
  "\"minimum\": 3e-07},\"voltage\": {\"a\": {\"channel\": \"AN17\",\"signed\": fals"
  "e},\"b\": {\"channel\": \"AN23\",\"signed\": false},\"c\": {\"channel\": \"AN22"
  "\",\"signed\": false},\"dcLink\": {\"channel\": \"AN15\",\"signed\": true}}},\"c"
  "omparator\": {\"inverted\": false,\"source\": \"CMP1C\",\"threshold\": 0.95},\"d"
  "ebugger\": {\"channel\": 3},\"gpio\": {\"MCAF_BUTTON1\": {\"direction\": \"input"
  "\",\"pin\": \"RE11\",\"polarity\": \"active-high\"},\"MCAF_BUTTON2\": {\"directi"
  "on\": \"input\",\"pin\": \"RE12\",\"polarity\": \"active-high\"},\"MCAF_LED1\": "
  "{\"direction\": \"output\",\"pin\": \"RE6\",\"polarity\": \"active-high\"},\"MCA"
  "F_LED2\": {\"direction\": \"output\",\"pin\": \"RE7\",\"polarity\": \"active-hig"
  "h\"},\"MCAF_TESTPOINT1\": {\"direction\": \"output\",\"pin\": \"RE4\",\"polarity"
  "\": \"active-high\"}},\"opamp\": {\"enabled\": [1,2,3]},\"oscillator\": {\"clock"
  "Source\": \"internal FRC\",\"inputClockFrequency\": 8000000},\"pwm\": {\"fault\""
  ": {\"polarity\": \"active-high\",\"source\": \"CMP1\"},\"generators\": {\"a\": 1"
  ",\"b\": 2,\"c\": 4},\"polarity\": {\"lower\": \"active-high\",\"upper\": \"activ"
  "e-high\"}},\"qei\": {\"pins\": {\"A\": \"RC12\",\"B\": \"RC13\",\"Z\": \"RC14\"}"
  "},\"uart\": {\"pins\": {\"RX\": \"RD14\",\"TX\": \"RD13\"}}}},\"idc\": {\"units"
  "\": \"A\"},\"sampling_time\": {\"current\": 5e-05,\"velocity\": 0.001},\"process"
  "or\": {\"clock_frequency\": 100000000.0,\"device\": \"dsPIC33CK256MP508\"}},\"co"
  "nfig\": {\"ui\": {\"content\": {\"current_measure-method\": \"triple_channel\","
  "\"current_measure-single_channel-minimumTime\": 2.0,\"current_measure-single_cha"
  "nnel-sampleDelay\": 0.0,\"current_measure-opamp-full_input_range\": true,\"curre"
  "nt_measure-offset_cal-range\": 0.04,\"estimator-type\": \"zsmt\",\"estimator-act"
  "ive-pll\": true,\"estimator-active-smo\": false,\"estimator-active-qei\": false,"
  "\"estimator-active-atpll\": false,\"estimator-active-zsmt\": false,\"estimator-a"
  "ctive-ideal\": false,\"operation-min_velocity_ratio\": 0.25,\"operation-startup_"
  "velocity_ratio\": 0.2744,\"operation-max_velocity_ratio\": 1.25,\"operation-full"
  "scale_base_ratio\": 1.5,\"operation-outer_loop_type\": \"velocity\",\"operation-"
  "saliency-threshold\": 1.25,\"operation-slewrate-accel\": 0.5,\"operation-slewrat"
  "e-decel\": 1.0,\"operation-dyn_current_type\": \"none\",\"operation-stopping-typ"
  "e\": \"minimal_impact\",\"operation-stopping-closed_loop_parameters-speed\": 0.0"
  "5,\"operation-stopping-closed_loop_parameters-time\": 0.5,\"operation-stopping-c"
  "oastdown-end_velocity\": 0.05,\"operation-stopping-coastdown-time\": 1.2,\"fault"
  "_inject-get_tf-div0\": false,\"fault_inject-get_tf-missing_data\": false,\"fault"
  "_inject-get_tf-raise_value_error\": false,\"fault_inject-get_tf-raise_custom_err"
  "or\": false,\"fault_inject-tf-tf_null\": false,\"fault_inject-tf-tf_jy\": false,"
  "\"fault_inject-tf-tf_jyex\": false,\"fault_inject-tf-div0\": false,\"fault_injec"
  "t-tf-tau\": 0.0,\"flux_control-method\": \"none\",\"flux_control-eqn_based-ilimi"
  "t-region_type\": \"quadratic\",\"flux_control-eqn_based-ilimit-id_limit\": 0.7,"
  "\"flux_control-eqn_based-ilimit-iq_limit\": 0.95,\"flux_control-eqn_based-fluxwe"
  "ak_enable\": false,\"flux_control-eqn_based-fw-vdq_limit\": 0.95,\"flux_control-"
  "eqn_based-mtpa_enable\": false,\"deadtimecomp-method\": \"none\",\"deadtimecomp-"
  "perphase-current_sign_band\": 0.02,\"deadtimecomp-perphase-forward_gain\": 0.0,"
  "\"deadtimecomp-perphase-feedback_gain\": 0.0,\"fault_detect-margin_uv\": 2.0,\"f"
  "ault_detect-margin_ov\": 2.0,\"fault_detect-stall_detect_enable\": false,\"start"
  "up-Istartup\": 0.75,\"startup-t_rampup\": 25.0,\"startup-t_align\": 0.0,\"startu"
  "p-min_total_accel_time\": 250.0,\"startup-torque_scale_accel\": 0.15,\"startup-t"
  "orque_scale_slow_accel\": 0.2,\"startup-t_hold\": 0.0,\"startup-omega0\": 0.2,\""
  "startup-theta_converge_rate\": 1.0,\"startup-method\": \"zsmt_dsat\",\"startup-d"
  "amping-Imax\": 0.133,\"startup-damping-gainmax\": 40.0,\"startup-damping-omega_m"
  "in\": 0.4,\"overmodulation-vd_limit\": 1.0,\"overmodulation-vq_limit\": 1.15,\"o"
  "vermodulation-include_duty_clipping\": true,\"atpll-tau1\": 0.1,\"atpll-tau2\": "
  "2.19,\"atpll-kp\": 1.9,\"atpll-ki\": 30.0,\"pll-tau\": 2.19,\"pll-omega1\": 116."
  "5,\"pll-velocity_filter_threshold\": 1.0,\"smo-velocity_loop_cutoff\": 0.3,\"enc"
  "oder-lines\": 250.0,\"encoder-index_present\": false,\"encoder-tracking_loop-tau"
  "\": 1.5,\"encoder-qei_sync-method\": \"align\",\"encoder-qei_sync-align-t_align"
  "\": 0.5,\"encoder-qei_sync-align-angle_shift\": 30.0,\"encoder-qei_sync-align-an"
  "gle_init\": -30.0,\"encoder-qei_sync-align_sweep-sweep_rate_pow\": 1.0,\"encoder"
  "-qei_sync-align_sweep-setup_angle\": 45.0,\"encoder-qei_sync-pullout-pullout_sli"
  "p\": 0.117,\"zsmt-excitation-kV\": 0.12,\"zsmt-excitation-kI\": 0.1,\"zsmt-pll-z"
  "eta\": 1.5,\"zsmt-pll-tau\": 10.0,\"zsmt-pll-tau_lpf\": 0.0,\"zsmt-pll-execution"
  "_divider\": 2.0,\"zsmt-startup-align_delay\": 1.0,\"zsmt-startup-pll_lock_time\""
  ": 1.0,\"zsmt-startup-speed_limit\": 0.015,\"zsmt-startup-current_limit\": 0.3,\""
  "zsmt-startup-probe_current\": 0.3,\"zsmt-startup-probe_duration\": 10.0,\"zsmt-s"
  "tartup-probe_slew_time\": 1.5,\"zsmt-startup-probe_blanking_time\": 4.0,\"zsmt-h"
  "ybrid-type\": \"minotaur\",\"zsmt-minotaur-voltage_limit-vd\": 0.45,\"zsmt-minot"
  "aur-voltage_limit-vq\": 0.78,\"zsmt-minotaur-converge-angle\": 10.0,\"zsmt-minot"
  "aur-converge-duration\": 2.0,\"zsmt-minotaur-velocity_threshold-slow\": 0.15,\"z"
  "smt-minotaur-velocity_threshold-transition\": 0.2,\"zsmt-minotaur-velocity_thres"
  "hold-fast\": 0.25,\"zsmt-angle_correction-current_gain\": 0.0,\"dyn_current1-pea"
  "k_factor\": 1.0,\"dyn_current1-horizon_factor\": 1.05,\"dyn_current1-tau\": 5.0,"
  "\"dyn_current1-nsamples\": 128.0,\"voltage_outerloop-tau_lpf\": 2.0,\"voltage_ou"
  "terloop-Kp\": 0.1,\"voltage_outerloop-tau\": 100.0,\"mcapi-isSquaredTau\": 1.0,"
  "\"mcapi-iqTau\": 1.0,\"mcapi-adcIsrUserFunctions_enable\": false,\"board_service"
  "-uiServiceTiming\": 1.0,\"board_service-uiButtonDebounceTime\": 7.0,\"board_serv"
  "ice-uiButtonLongPressTime\": 2.5,\"test_harness-perturbation_asymmetric\": false"
  ",\"test_harness-codegen-test_harness\": false,\"test_harness-codegen-test_profil"
  "ing\": false,\"adc-vtempbridge\": false,\"adc-temp_bridge_params-threshold\": 50"
  ".0,\"adc-temp_bridge_params-tau_lpf\": 10.0,\"adc-temp_bridge_params-slewrate\":"
  " 4.0,\"adc-vabsref\": false,\"adc-vphasea\": false,\"adc-vphaseb\": false,\"adc-"
  "vphasec\": false,\"diagnostics-method\": \"x2cscope\"},\"version\": {\"schema\":"
  " 6.0,\"motorBench\": \"2.55.0\",\"MCAF\": \"R9\"},\"status\": {\"valid\": true}}"
  "}}";
