/*
 * data_model_snapshot.c
 * 
 * Snapshot of code generation data model.
 * This information is included in the executable file
 * and does not affect any memory content in the embedded device.
 */
 
__attribute__((section("diagnostics_cinfo, info"), keep)) char MCAF_data_model_snapshot[] =
  "{\"motor\": {\"Tfr\": 0.0281,\"B\": 1.90141e-05,\"Lq\": 0.0004853,\"poleCount\":"
  " 4,\"rated_current\": 7.5,\"J\": 5.55319e-05,\"velocity\": {\"nominal\": 314.159"
  "265359,\"maximum\": 628.318530718,\"units\": \"rad\\/s\"},\"L\": 0.0004162,\"R\""
  ": 0.1859,\"current\": {\"maximum\": {\"continuous\": 7.5,\"peak\": 7.5},\"units"
  "\": \"A\"},\"Ld\": 0.0003471,\"Ke\": 0.0314613077567,\"id\": \"elra-ipm80s-24v\""
  "},\"controller\": {\"encoder\": {\"tracking_loop\": {\"zeta\": 1.5}},\"foc\": {"
  "\"feedback\": {\"voltage_delay\": 0}},\"pll\": {\"delay_match\": true,\"properti"
  "es\": {\"reference\": false},\"keInverseScaling\": 1.0},\"operation\": {\"min_de"
  "celeration_time\": null},\"dyn_current\": {\"maxgain\": 1.1},\"zsmt\": {\"errorL"
  "imit\": 0.99997,\"properties\": {\"independent\": true,\"reference\": false},\"d"
  "uration\": {\"lockDelay\": 0.05},\"probe\": {\"accumGain\": 1.0}},\"fault_detect"
  "\": {\"recovery\": {\"attempts\": 3}}},\"metadata\": {\"MCC\": {\"architecture\""
  ": \"melody\",\"peripherals\": {\"instances\": [{\"name\": \"ADC1\",\"type\": \"a"
  "dc\"},{\"name\": \"PWM\",\"type\": \"pwm_hs\"},{\"name\": \"QEI1\",\"type\": \"q"
  "ei\"},{\"name\": \"TMR1\",\"type\": \"timer\"},{\"name\": \"SCCP1\",\"type\": \""
  "timer\"},{\"name\": \"UART1\",\"type\": \"uart\"},{\"name\": \"OPA1\",\"type\": "
  "\"opa\"},{\"name\": \"OPA2\",\"type\": \"opa\"},{\"name\": \"OPA3\",\"type\": \""
  "opa\"},{\"name\": \"CMP1\",\"type\": \"cmp\"}]},\"version\": \"5.7.1\",\"periphe"
  "ral_library\": {\"name\": \"melody\",\"version\": \"NA\"}},\"data_model\": {\"sc"
  "hema_version\": 5},\"motorBench\": {\"commit_id\": \"cca205f0cfd3911d9402cd4a9bb"
  "65183b7cd48b6\",\"version\": \"2.50.0\"},\"MCAF\": {\"build\": {\"commit_id\": "
  "\"128946\",\"date_str\": \"2025 Apr 09\",\"hostname\": \"motor-control-mcaf-tags"
  "-builder-r8-2frc38-1-0700f-4pfpx-1fklf\",\"time\": 1744217130.6,\"time_iso\": \""
  "2025-04-09T16:45:30.604389\",\"time_str\": \"2025 Apr 09 16:45\",\"type\": \"rel"
  "ease\",\"username\": \"jenkins\",\"version\": \"R8\\/RC38\"},\"build_time\": 174"
  "4217130.6,\"build_time_iso\": \"2025-04-09T16:45:30.604389\",\"build_time_str\":"
  " \"2025 Apr 09 16:45\",\"commit_id\": \"128946\",\"version\": \"R8\\/RC38\"}},\""
  "scdata\": {\"setup\": {\"communications\": {\"baudrate\": 625000},\"analysis\": "
  "{\"spindown_time\": {\"units\": \"s\",\"value\": 1.0},\"max_motor_speed\": {\"un"
  "its\": \"rad\\/s mechanical\",\"value\": 2094.4}},\"calibration\": {\"vdc\": {\""
  "units\": \"V\",\"value\": 24.0},\"resistor\": {\"units\": \"ohms\",\"value\": 12"
  ".0}}}},\"autotune_result\": {\"current\": {\"Kp\": 0.218574077269,\"phase_margin"
  "\": 80.0,\"wc\": 686.86458694,\"Ki\": 150.130793299,\"pi_phase_lag\": 45.0},\"ve"
  "locity\": {\"Kp\": 0.0135818369396,\"phase_margin\": 65.0,\"wc\": 9.63501965242,"
  "\"Ki\": 0.0230743718954,\"pi_phase_lag\": 10.0}},\"code_generation_tag_map\": {"
  "\"application\": \"sample\",\"diagnostics\": \"x2cscope\"},\"operating_range\": "
  "{\"velocity\": {\"units_qualifier\": \"mechanical\",\"units\": \"rad\\/s\",\"min"
  "imum\": 261.7995}},\"build\": {\"hardware_spec\": \"mclv2:33ck256mp508_extopamp_"
  "pim\",\"normfactor_associations\": [{\"context\": null,\"annotations\": [{\"type"
  "refs\": [\"MCAF_U_CURRENT_ABC\",\"MCAF_U_CURRENT_ALPHABETA\",\"MCAF_U_CURRENT_DQ"
  "\",\"MCAF_U_CURRENT\",\"MCAF_MOTOR_DATA.omegaCtrl.outMin\",\"MCAF_MOTOR_DATA.ome"
  "gaCtrl.outMax\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR_DATA.om"
  "egaCtrl.integrator\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VOLTAG"
  "E_ABC\",\"MCAF_U_VOLTAGE_ALPHABETA\",\"MCAF_U_VOLTAGE_DQ\",\"MCAF_U_VOLTAGE\",\""
  "MCAF_MOTOR_DATA.idCtrl.outMin\",\"MCAF_MOTOR_DATA.idCtrl.outMax\",\"MCAF_MOTOR_D"
  "ATA.iqCtrl.outMin\",\"MCAF_MOTOR_DATA.iqCtrl.outMax\"],\"unit\": \"V\",\"q\": 15"
  "},{\"typerefs\": [\"MCAF_MOTOR_DATA.idCtrl.integrator\",\"MCAF_MOTOR_DATA.iqCtrl"
  ".integrator\"],\"unit\": \"V\",\"q\": 31},{\"typerefs\": [\"MCAF_U_DUTYCYCLE_ABC"
  "\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_ELEC\"],\"unit\": \"th"
  "eta_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_MECH\"],\"unit\": \"theta_m\","
  "\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_MECH\"],\"unit\": \"omega_m\",\"q\""
  ": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_ELEC\"],\"unit\": \"omega_e\",\"q\": 15}"
  ",{\"typerefs\": [\"MCAF_U_VELOCITY_DTHETA_ELEC_DT\"],\"unit\": \"dtheta_elec_dt"
  "\",\"q\": 15},{\"typerefs\": [\"MCAF_U_TEMPERATURE\"],\"unit\": \"Temperature\","
  "\"q\": 15},{\"typerefs\": [\"MCAF_U_DIMENSIONLESS\",\"MCAF_U_DIMENSIONLESS_SINCO"
  "S\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_NORMALIZED_GAIN\"],\"unit\""
  ": 1,\"q\": 14}]}]},\"drive\": {\"iout\": {\"measurement\": {\"compensation\": {"
  "\"channels\": [\"a\",\"b\"],\"values\": {\"a\": [1.0,0.0],\"b\": [0.0,1.0]},\"of"
  "fset\": {\"range\": 0.03125,\"samples\": 128,\"filterGain\": 0.25}}},\"time_cons"
  "tant\": 1.84e-07,\"fullscale\": 21.8,\"maximum\": {\"continuous\": 14.1},\"units"
  "\": \"A\"},\"estimator\": {\"type\": \"pll\",\"runtimeSelect\": false,\"atpll\":"
  " {\"tau1\": 0.0001,\"tau2\": 0.00219,\"kpfactor\": 1.9,\"kifactor\": 30},\"smo\""
  ": {\"ke_low_limit\": 0.01},\"omega1\": 732.0,\"tau\": 0.00219},\"flux_control\":"
  " {\"emag_tau\": 0.001638,\"idref_tau\": 0.006552},\"temperature\": {\"fullscale"
  "\": 327.68,\"units\": \"C\"},\"pwm\": {\"adc_sampling_delay\": 0,\"period\": 5e-"
  "05,\"duty_cycle\": {\"maximum\": 0.975,\"minimum\": 0.009},\"deadtime\": 2e-06},"
  "\"mcaf\": {\"adc\": {\"triggerSettings\": {\"noTrigger\": \"NO_TRIGGER\",\"trigg"
  "er1\": \"PWM1_TRIGGER1\",\"trigger2\": \"PWM1_TRIGGER2\"},\"channels\": {\"prefi"
  "x\": \"MCAF_ADC_\",\"critical\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"PHASEC"
  "_CURRENT\",\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"required\": {\"single_channe"
  "l\": [\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\",\"POTENTIOMETER\"],\"dual_channel\":"
  " [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"DCLINK_VOLTAGE\",\"POTENTIOMETER\"],\""
  "triple_channel\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\"DC"
  "LINK_VOLTAGE\",\"POTENTIOMETER\"]},\"optional\": [\"PHASEA_VOLTAGE\",\"PHASEB_VO"
  "LTAGE\",\"PHASEC_VOLTAGE\",\"BRIDGE_TEMPERATURE\",\"ABSREF_VOLTAGE\"],\"fullList"
  "\": [{\"name\": \"PHASEA_CURRENT\",\"c_fragment\": \"PhaseACurrent\",\"descripti"
  "on\": \"phase A current\",\"type\": \"current\"},{\"name\": \"PHASEB_CURRENT\","
  "\"c_fragment\": \"PhaseBCurrent\",\"description\": \"phase B current\",\"type\":"
  " \"current\"},{\"name\": \"PHASEC_CURRENT\",\"c_fragment\": \"PhaseCCurrent\",\""
  "description\": \"phase C current\",\"type\": \"current\"},{\"name\": \"PHASEA_VO"
  "LTAGE\",\"c_fragment\": \"PhaseAVoltage\",\"description\": \"phase A voltage\","
  "\"type\": \"voltage\"},{\"name\": \"PHASEB_VOLTAGE\",\"c_fragment\": \"PhaseBVol"
  "tage\",\"description\": \"phase B voltage\",\"type\": \"voltage\"},{\"name\": \""
  "PHASEC_VOLTAGE\",\"c_fragment\": \"PhaseCVoltage\",\"description\": \"phase C vo"
  "ltage\",\"type\": \"voltage\"},{\"name\": \"DCLINK_CURRENT\",\"c_fragment\": \"D"
  "CLinkCurrent\",\"description\": \"DC link current\",\"type\": \"current\"},{\"na"
  "me\": \"DCLINK_VOLTAGE\",\"c_fragment\": \"DCLinkVoltage\",\"description\": \"DC"
  " link voltage\",\"type\": \"voltage\"},{\"name\": \"POTENTIOMETER\",\"c_fragment"
  "\": \"Potentiometer\",\"description\": \"potentiometer voltage\",\"type\": \"vol"
  "tage\"},{\"name\": \"BRIDGE_TEMPERATURE\",\"c_fragment\": \"BridgeTemperature\","
  "\"description\": \"bridge temperature voltage\",\"type\": \"voltage\"},{\"name\""
  ": \"ABSREF_VOLTAGE\",\"c_fragment\": \"AbsoluteReferenceVoltage\",\"description"
  "\": \"absolute reference voltage\",\"type\": \"voltage\"}]}}},\"metadata\": {\"n"
  "ame\": \"dsPIC33CK LVMC\",\"id\": \"lvmc-33ck\"},\"vdc\": {\"nominal\": 24.0,\"t"
  "ime_constant\": 0.0003147,\"fullscale\": 71.3,\"maximum\": 26.0,\"units\": \"V\""
  ",\"minimum\": 14.0},\"configuration\": {\"characteristics\": {\"current\": {\"dc"
  "Link\": {\"fullscale\": 21.8,\"timeConstant\": 1.84e-07},\"phase\": {\"fullscale"
  "\": 21.8,\"maximum\": {\"continuous\": 14.1},\"timeConstant\": 1.84e-07}},\"devi"
  "ce\": \"dsPIC33CK256MP508\",\"pwm\": {\"deadTime\": {\"default\": 1e-06,\"maximu"
  "m\": 6e-06,\"minimum\": 6.7e-07},\"dutyCycle\": {\"maximum\": 0.975,\"minimum\":"
  " 0.009},\"frequency\": {\"default\": 20000,\"maximum\": 100000,\"minimum\": 1000"
  "}},\"voltage\": {\"dcLink\": {\"default\": 24.0,\"fullscale\": 71.3,\"maximum\":"
  " 26.0,\"minimum\": 14.0,\"timeConstant\": 0.0003147},\"phase\": {\"fullscale\": "
  "71.3,\"timeConstant\": 0.0003147}}},\"identification\": {\"description\": \"dsPI"
  "C33CK Low Voltage Motor Control (LVMC) Development Board\",\"displayName\": \"ds"
  "PIC33CK LVMC\",\"id\": \"lvmc-33ck\"},\"peripherals\": {\"adc\": {\"current\": {"
  "\"a\": {\"channel\": \"AN0\",\"inverted\": true,\"signed\": true},\"b\": {\"chan"
  "nel\": \"AN1\",\"inverted\": true,\"signed\": true},\"c\": {\"channel\": \"AN10"
  "\",\"inverted\": true,\"signed\": true},\"dcLink\": {\"channel\": \"AN4\",\"inve"
  "rted\": false,\"signed\": true}},\"other\": {\"bridgeTemperature\": {\"channel\""
  ": \"AN12\",\"gain\": 0.50354,\"offset\": 0.5,\"signed\": false},\"potentiometer"
  "\": {\"channel\": \"AN11\",\"signed\": true}},\"samplingTime\": {\"default\": 3e"
  "-07,\"maximum\": 3e-07,\"minimum\": 3e-07},\"voltage\": {\"a\": {\"channel\": \""
  "AN17\",\"signed\": false},\"b\": {\"channel\": \"AN23\",\"signed\": false},\"c\""
  ": {\"channel\": \"AN22\",\"signed\": false},\"dcLink\": {\"channel\": \"AN15\","
  "\"signed\": true}}},\"comparator\": {\"inverted\": false,\"source\": \"CMP1C\","
  "\"threshold\": 0.95},\"debugger\": {\"channel\": 3},\"gpio\": {\"MCAF_BUTTON1\":"
  " {\"direction\": \"input\",\"pin\": \"RE11\",\"polarity\": \"active-high\"},\"MC"
  "AF_BUTTON2\": {\"direction\": \"input\",\"pin\": \"RE12\",\"polarity\": \"active"
  "-high\"},\"MCAF_LED1\": {\"direction\": \"output\",\"pin\": \"RE6\",\"polarity\""
  ": \"active-high\"},\"MCAF_LED2\": {\"direction\": \"output\",\"pin\": \"RE7\",\""
  "polarity\": \"active-high\"},\"MCAF_TESTPOINT1\": {\"direction\": \"output\",\"p"
  "in\": \"RE4\",\"polarity\": \"active-high\"}},\"opamp\": {\"enabled\": [1,2,3]},"
  "\"oscillator\": {\"clockSource\": \"internal FRC\",\"inputClockFrequency\": 8000"
  "000},\"pwm\": {\"fault\": {\"polarity\": \"active-high\",\"source\": \"CMP1\"},"
  "\"generators\": {\"a\": 1,\"b\": 2,\"c\": 4},\"polarity\": {\"lower\": \"active-"
  "high\",\"upper\": \"active-high\"}},\"qei\": {\"pins\": {\"A\": \"RC12\",\"B\": "
  "\"RC13\",\"Z\": \"RC14\"}},\"uart\": {\"pins\": {\"RX\": \"RD14\",\"TX\": \"RD13"
  "\"}}}},\"idc\": {\"units\": \"A\"},\"sampling_time\": {\"current\": 5e-05,\"velo"
  "city\": 0.001},\"processor\": {\"clock_frequency\": 100000000.0,\"device\": \"ds"
  "PIC33CK256MP508\"}},\"config\": {\"ui\": {\"content\": {\"current_measure-method"
  "\": \"triple_channel\",\"current_measure-single_channel-minimumTime\": 2.0,\"cur"
  "rent_measure-single_channel-sampleDelay\": 0.0,\"current_measure-opamp-full_inpu"
  "t_range\": true,\"estimator-type\": \"zsmt\",\"estimator-active-pll\": true,\"es"
  "timator-active-qei\": false,\"estimator-active-smo\": false,\"estimator-active-a"
  "tpll\": false,\"estimator-active-zsmt\": false,\"estimator-active-ideal\": false"
  ",\"operation-min_velocity_ratio\": 0.25,\"operation-startup_velocity_ratio\": 0."
  "2744,\"operation-max_velocity_ratio\": 1.25,\"operation-fullscale_base_ratio\": "
  "1.5,\"operation-outer_loop_type\": \"velocity\",\"operation-saliency-threshold\""
  ": 1.25,\"operation-slewrate-accel\": 0.5,\"operation-slewrate-decel\": 1.0,\"ope"
  "ration-dyn_current_type\": \"none\",\"operation-stopping-type\": \"minimal_impac"
  "t\",\"operation-stopping-closed_loop_parameters-speed\": 0.05,\"operation-stoppi"
  "ng-closed_loop_parameters-time\": 0.5,\"operation-stopping-coastdown-end_velocit"
  "y\": 0.05,\"operation-stopping-coastdown-time\": 1.2,\"fault_inject-get_tf-div0"
  "\": false,\"fault_inject-get_tf-missing_data\": false,\"fault_inject-get_tf-rais"
  "e_value_error\": false,\"fault_inject-get_tf-raise_custom_error\": false,\"fault"
  "_inject-tf-tf_null\": false,\"fault_inject-tf-tf_jy\": false,\"fault_inject-tf-t"
  "f_jyex\": false,\"fault_inject-tf-div0\": false,\"fault_inject-tf-tau\": 0.0,\"f"
  "lux_control-method\": \"none\",\"flux_control-eqn_based-ilimit-region_type\": \""
  "quadratic\",\"flux_control-eqn_based-ilimit-id_limit\": 0.7,\"flux_control-eqn_b"
  "ased-ilimit-iq_limit\": 0.95,\"flux_control-eqn_based-fluxweak_enable\": false,"
  "\"flux_control-eqn_based-fw-vdq_limit\": 0.95,\"flux_control-eqn_based-mtpa_enab"
  "le\": false,\"deadtimecomp-method\": \"none\",\"deadtimecomp-perphase-current_si"
  "gn_band\": 0.02,\"deadtimecomp-perphase-forward_gain\": 0.0,\"deadtimecomp-perph"
  "ase-feedback_gain\": 0.0,\"fault_detect-margin_uv\": 2.0,\"fault_detect-margin_o"
  "v\": 2.0,\"fault_detect-stall_detect_enable\": false,\"startup-Istartup\": 0.75,"
  "\"startup-t_rampup\": 25.0,\"startup-t_align\": 0.0,\"startup-min_total_accel_ti"
  "me\": 250.0,\"startup-torque_scale_accel\": 0.15,\"startup-torque_scale_slow_acc"
  "el\": 0.2,\"startup-t_hold\": 0.0,\"startup-omega0\": 0.2,\"startup-theta_conver"
  "ge_rate\": 1.0,\"startup-method\": \"zsmt_dsat\",\"startup-damping-Imax\": 0.1,"
  "\"startup-damping-gainmax\": 40.0,\"startup-damping-omega_min\": 0.4,\"overmodul"
  "ation-vd_limit\": 1.0,\"overmodulation-vq_limit\": 1.15,\"overmodulation-include"
  "_duty_clipping\": true,\"pll-tau\": 2.19,\"pll-omega1\": 116.5,\"pll-velocity_fi"
  "lter_threshold\": 1.0,\"encoder-lines\": 250.0,\"encoder-index_present\": false,"
  "\"encoder-tracking_loop-tau\": 1.5,\"encoder-qei_sync-method\": \"align\",\"enco"
  "der-qei_sync-align-t_align\": 0.5,\"encoder-qei_sync-align-angle_shift\": 30.0,"
  "\"encoder-qei_sync-align-angle_init\": -30.0,\"encoder-qei_sync-align_sweep-swee"
  "p_rate_pow\": 1.0,\"encoder-qei_sync-align_sweep-setup_angle\": 45.0,\"encoder-q"
  "ei_sync-pullout-pullout_slip\": 0.117,\"zsmt-excitation-kV\": 0.12,\"zsmt-excita"
  "tion-kI\": 0.1,\"zsmt-pll-zeta\": 1.5,\"zsmt-pll-tau\": 10.0,\"zsmt-pll-tau_lpf"
  "\": 0.0,\"zsmt-pll-execution_divider\": 2.0,\"zsmt-startup-align_delay\": 1.0,\""
  "zsmt-startup-pll_lock_time\": 1.0,\"zsmt-startup-speed_limit\": 0.015,\"zsmt-sta"
  "rtup-current_limit\": 0.3,\"zsmt-startup-probe_current\": 0.3,\"zsmt-startup-pro"
  "be_duration\": 10.0,\"zsmt-startup-probe_slew_time\": 1.5,\"zsmt-startup-probe_b"
  "lanking_time\": 4.0,\"zsmt-hybrid-type\": \"minotaur\",\"zsmt-minotaur-voltage_l"
  "imit-vd\": 0.45,\"zsmt-minotaur-voltage_limit-vq\": 0.78,\"zsmt-minotaur-converg"
  "e-angle\": 10.0,\"zsmt-minotaur-converge-duration\": 2.0,\"zsmt-minotaur-velocit"
  "y_threshold-slow\": 0.15,\"zsmt-minotaur-velocity_threshold-transition\": 0.2,\""
  "zsmt-minotaur-velocity_threshold-fast\": 0.25,\"zsmt-angle_correction-current_ga"
  "in\": 0.0,\"dyn_current1-peak_factor\": 1.0,\"dyn_current1-horizon_factor\": 1.0"
  "5,\"dyn_current1-tau\": 5.0,\"dyn_current1-nsamples\": 128.0,\"voltage_outerloop"
  "-tau_lpf\": 2.0,\"voltage_outerloop-Kp\": 0.1,\"voltage_outerloop-tau\": 100.0,"
  "\"mcapi-isSquaredTau\": 1.0,\"mcapi-iqTau\": 1.0,\"mcapi-adcIsrUserFunctions_ena"
  "ble\": false,\"board_service-uiServiceTiming\": 1.0,\"board_service-uiButtonDebo"
  "unceTime\": 7.0,\"board_service-uiButtonLongPressTime\": 2.5,\"test_harness-pert"
  "urbation_asymmetric\": false,\"adc-vtempbridge\": false,\"adc-temp_bridge_params"
  "-threshold\": 50.0,\"adc-temp_bridge_params-tau_lpf\": 10.0,\"adc-temp_bridge_pa"
  "rams-slewrate\": 4.0,\"adc-vabsref\": false,\"adc-vphasea\": false,\"adc-vphaseb"
  "\": false,\"adc-vphasec\": false,\"diagnostics-method\": \"x2cscope\"},\"version"
  "\": {\"schema\": 5.0,\"motorBench\": \"2.50.0\",\"MCAF\": \"R8\"},\"status\": {"
  "\"valid\": true}}}}";