/*
 * data_model_snapshot.c
 * 
 * Snapshot of code generation data model.
 * This information is included in the executable file
 * and does not affect any memory content in the embedded device.
 */
 
__attribute__((section("diagnostics_cinfo, info"), keep)) char MCAF_data_model_snapshot[] =
  "{\"motor\": {\"Tfr\": 0.012851,\"B\": 4.5886638e-05,\"Lq\": 0.0001325,\"poleCoun"
  "t\": 8,\"rated_current\": 9.01,\"J\": 3.0080946e-05,\"velocity\": {\"nominal\": "
  "418.879020479,\"maximum\": 418.879020479,\"units\": \"rad\\/s\"},\"L\": 0.000117"
  "25,\"R\": 0.241,\"current\": {\"maximum\": {\"continuous\": 9.01,\"peak\": 23.5}"
  ",\"units\": \"A\"},\"Ld\": 0.000102,\"Ke\": 0.0371291616747,\"id\": \"ACT57BLF02"
  "\"},\"controller\": {\"encoder\": {\"tracking_loop\": {\"zeta\": 1.5}},\"foc\": "
  "{\"feedback\": {\"voltage_delay\": 0}},\"pll\": {\"delay_match\": true,\"propert"
  "ies\": {\"reference\": false},\"keInverseScaling\": 1.0},\"operation\": {\"min_d"
  "eceleration_time\": null},\"dyn_current\": {\"maxgain\": 1.1},\"zsmt\": {\"error"
  "Limit\": 0.99997,\"properties\": {\"independent\": true,\"reference\": false},\""
  "duration\": {\"lockDelay\": 0.05},\"probe\": {\"accumGain\": 1.0}},\"fault_detec"
  "t\": {\"recovery\": {\"attempts\": 3}}},\"metadata\": {\"MCC\": {\"architecture"
  "\": \"melody\",\"peripherals\": {\"instances\": [{\"name\": \"ADC1\",\"type\": "
  "\"adc\"},{\"name\": \"PWM\",\"type\": \"pwm_hs\"},{\"name\": \"QEI1\",\"type\": "
  "\"qei\"},{\"name\": \"SCCP1\",\"type\": \"timer\"},{\"name\": \"TMR1\",\"type\":"
  " \"timer\"},{\"name\": \"UART1\",\"type\": \"uart\"},{\"name\": \"OPA1\",\"type"
  "\": \"opa\"},{\"name\": \"OPA2\",\"type\": \"opa\"},{\"name\": \"OPA3\",\"type\""
  ": \"opa\"},{\"name\": \"CMP3\",\"type\": \"cmp\"}]},\"version\": \"5.8.4\",\"per"
  "ipheral_library\": {\"name\": \"melody\",\"version\": \"NA\"}},\"data_model\": {"
  "\"schema_version\": 5},\"motorBench\": {\"commit_id\": \"e295e8191836011540cb544"
  "beb5347d8147868da\",\"version\": \"2.55.0\"},\"MCAF\": {\"build\": {\"com"
  "mit_id\": \"132024\",\"date_str\": \"2026 Feb 13\",\"hostname\": \"motor-control"
  "-mcaf-tags-builder-r9-2frc31-1-4qzv8-0zfbw-3kggr\",\"time\": 1771007857.63,\"tim"
  "e_iso\": \"2026-02-13T18:37:37.630250\",\"time_str\": \"2026 Feb 13 18:37\",\"ty"
  "pe\": \"release\",\"username\": \"jenkins\",\"version\": \"R9\\/RC31\"},\"build_"
  "time\": 1771007857.63,\"build_time_iso\": \"2026-02-13T18:37:37.630250\",\"build"
  "_time_str\": \"2026 Feb 13 18:37\",\"commit_id\": \"132024\",\"version\": \"R9\\"
  "/RC31\"}},\"scdata\": {\"setup\": {\"communications\": {\"baudrate\": 625000},\""
  "analysis\": {\"spindown_time\": {\"units\": \"s\",\"value\": 1.0},\"max_motor_sp"
  "eed\": {\"units\": \"rad\\/s mechanical\",\"value\": 2094.4}},\"calibration\": {"
  "\"vdc\": {\"units\": \"V\",\"value\": 24.0},\"resistor\": {\"units\": \"ohms\","
  "\"value\": 12.0}}}},\"autotune_result\": {\"current\": {\"Kp\": 0.253506382963,"
  "\"phase_margin\": 80.0,\"wc\": 2498.28961077,\"Ki\": 633.332362818,\"pi_phase_la"
  "g\": 45.0},\"velocity\": {\"Kp\": 0.00787914308564,\"phase_margin\": 65.0,\"wc\""
  ": 12.5993025594,\"Ki\": 0.0175042804788,\"pi_phase_lag\": 10.0}},\"code_generati"
  "on_tag_map\": {\"application\": \"sample\",\"diagnostics\": \"x2cscope\"},\"oper"
  "ating_range\": {\"velocity\": {\"units_qualifier\": \"mechanical\",\"units\": \""
  "rad\\/s\",\"minimum\": 130.89975}},\"build\": {\"hardware_spec\": \"mclv2:33ck25"
  "6mp508_extopamp_pim\",\"normfactor_associations\": [{\"context\": null,\"annotat"
  "ions\": [{\"typerefs\": [\"MCAF_U_CURRENT_ABC\",\"MCAF_U_CURRENT_ALPHABETA\",\"M"
  "CAF_U_CURRENT_DQ\",\"MCAF_U_CURRENT\",\"MCAF_MOTOR_DATA.omegaCtrl.outMin\",\"MCA"
  "F_MOTOR_DATA.omegaCtrl.outMax\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"MC"
  "AF_MOTOR_DATA.omegaCtrl.integrator\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": "
  "[\"MCAF_U_VOLTAGE_ABC\",\"MCAF_U_VOLTAGE_ALPHABETA\",\"MCAF_U_VOLTAGE_DQ\",\"MCA"
  "F_U_VOLTAGE\",\"MCAF_MOTOR_DATA.idCtrl.outMin\",\"MCAF_MOTOR_DATA.idCtrl.outMax"
  "\",\"MCAF_MOTOR_DATA.iqCtrl.outMin\",\"MCAF_MOTOR_DATA.iqCtrl.outMax\"],\"unit\""
  ": \"V\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR_DATA.idCtrl.integrator\",\"MCAF_"
  "MOTOR_DATA.iqCtrl.integrator\"],\"unit\": \"V\",\"q\": 31},{\"typerefs\": [\"MCA"
  "F_U_DUTYCYCLE_ABC\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_ELEC"
  "\"],\"unit\": \"theta_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_MECH\"],\"un"
  "it\": \"theta_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_MECH\"],\"unit\":"
  " \"omega_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_ELEC\"],\"unit\": \"om"
  "ega_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_DTHETA_ELEC_DT\"],\"unit\":"
  " \"dtheta_elec_dt\",\"q\": 15},{\"typerefs\": [\"MCAF_U_TEMPERATURE\"],\"unit\":"
  " \"Temperature\",\"q\": 15},{\"typerefs\": [\"MCAF_U_DIMENSIONLESS\",\"MCAF_U_DI"
  "MENSIONLESS_SINCOS\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_NORMALIZED"
  "_GAIN\"],\"unit\": 1,\"q\": 14},{\"typerefs\": [\"MCAF_U_NORMALIZED_Q15\"],\"uni"
  "t\": 1,\"q\": 15}]}]},\"drive\": {\"iout\": {\"measurement\": {\"compensation\":"
  " {\"channels\": [\"a\",\"b\"],\"values\": {\"a\": [1.0,0.0],\"b\": [0.0,1.0]},\""
  "offset\": {\"samples\": 128,\"filterGain\": 0.25},\"gain\": {\"samples\": 128}}}"
  ",\"time_constant\": 5.97e-07,\"fullscale\": 22.04,\"maximum\": {\"continuous\": "
  "16.0,\"peak\": 16.0},\"units\": \"A\"},\"estimator\": {\"type\": \"pll\",\"runti"
  "meSelect\": false,\"smo\": {\"ke_low_limit\": 0.01},\"omega1\": 732.0,\"tau\": 0"
  ".00219},\"flux_control\": {\"emag_tau\": 0.001638,\"idref_tau\": 0.006552},\"tem"
  "perature\": {\"fullscale\": 327.68,\"units\": \"C\"},\"pwm\": {\"adc_sampling_de"
  "lay\": 0,\"period\": 5e-05,\"duty_cycle\": {\"maximum\": 0.945,\"minimum\": 0.01"
  "4},\"deadtime\": 5.9e-07},\"mcaf\": {\"adc\": {\"triggerSettings\": {\"noTrigger"
  "\": \"NO_TRIGGER\",\"trigger1\": \"PWM1_TRIGGER1\",\"trigger2\": \"PWM1_TRIGGER2"
  "\"},\"channels\": {\"prefix\": \"MCAF_ADC_\",\"critical\": [\"PHASEA_CURRENT\","
  "\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"r"
  "equired\": {\"single_channel\": [\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"dual_c"
  "hannel\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"DCLINK_VOLTAGE\"],\"triple_ch"
  "annel\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_VOLT"
  "AGE\"]},\"optional\": [\"POTENTIOMETER\",\"PHASEA_VOLTAGE\",\"PHASEB_VOLTAGE\","
  "\"PHASEC_VOLTAGE\",\"BRIDGE_TEMPERATURE\",\"ABSREF_VOLTAGE\"],\"fullList\": [{\""
  "name\": \"PHASEA_CURRENT\",\"c_fragment\": \"PhaseACurrent\",\"description\": \""
  "phase A current\",\"type\": \"current\"},{\"name\": \"PHASEB_CURRENT\",\"c_fragm"
  "ent\": \"PhaseBCurrent\",\"description\": \"phase B current\",\"type\": \"curren"
  "t\"},{\"name\": \"PHASEC_CURRENT\",\"c_fragment\": \"PhaseCCurrent\",\"descripti"
  "on\": \"phase C current\",\"type\": \"current\"},{\"name\": \"PHASEA_VOLTAGE\","
  "\"c_fragment\": \"PhaseAVoltage\",\"description\": \"phase A voltage\",\"type\":"
  " \"voltage\"},{\"name\": \"PHASEB_VOLTAGE\",\"c_fragment\": \"PhaseBVoltage\",\""
  "description\": \"phase B voltage\",\"type\": \"voltage\"},{\"name\": \"PHASEC_VO"
  "LTAGE\",\"c_fragment\": \"PhaseCVoltage\",\"description\": \"phase C voltage\","
  "\"type\": \"voltage\"},{\"name\": \"DCLINK_CURRENT\",\"c_fragment\": \"DCLinkCur"
  "rent\",\"description\": \"DC link current\",\"type\": \"current\"},{\"name\": \""
  "DCLINK_VOLTAGE\",\"c_fragment\": \"DCLinkVoltage\",\"description\": \"DC link vo"
  "ltage\",\"type\": \"voltage\"},{\"name\": \"POTENTIOMETER\",\"c_fragment\": \"Po"
  "tentiometer\",\"description\": \"potentiometer voltage\",\"type\": \"voltage\"},"
  "{\"name\": \"BRIDGE_TEMPERATURE\",\"c_fragment\": \"BridgeTemperature\",\"descri"
  "ption\": \"bridge temperature voltage\",\"type\": \"voltage\"},{\"name\": \"ABSR"
  "EF_VOLTAGE\",\"c_fragment\": \"AbsoluteReferenceVoltage\",\"description\": \"abs"
  "olute reference voltage\",\"type\": \"voltage\"}]}}},\"metadata\": {\"name\": \""
  "MCLV-48V-300W\",\"id\": \"mclv-48v-300w\"},\"vdc\": {\"time_constant\": 2.87e-05"
  ",\"nominal\": 24.0,\"fullscale\": 75.9,\"maximum\": 26.0,\"units\": \"V\",\"mini"
  "mum\": 16.0},\"configuration\": {\"characteristics\": {\"current\": {\"dcLink\":"
  " {\"fullscale\": 22.04,\"timeConstant\": 5.97e-07},\"phase\": {\"fullscale\": 22"
  ".04,\"maximum\": {\"continuous\": 16.0},\"timeConstant\": 5.97e-07}},\"device\":"
  " \"dsPIC33AK128MC106\",\"powerOn\": {\"delay\": {\"maximum\": 0.05}},\"pwm\": {"
  "\"deadTime\": {\"default\": 5.9e-07,\"maximum\": 6e-06,\"minimum\": 3.85e-07},\""
  "dutyCycle\": {\"maximum\": 0.945,\"minimum\": 0.014},\"frequency\": {\"default\""
  ": 20000,\"maximum\": 50000,\"minimum\": 10000}},\"voltage\": {\"dcLink\": {\"def"
  "ault\": 24.0,\"fullscale\": 75.9,\"maximum\": 26.0,\"minimum\": 16.0,\"timeConst"
  "ant\": 2.87e-05},\"phase\": {\"fullscale\": 75.9,\"timeConstant\": 2.87e-05}}},"
  "\"identification\": {\"description\": \"MCLV-48V-300W Inverter Board\",\"display"
  "Name\": \"MCLV-48V-300W\",\"id\": \"mclv-48v-300w\",\"pim_id\": \"33ak128mc106_d"
  "im\"},\"peripherals\": {\"adc\": {\"current\": {\"a\": {\"channel\": \"AD1AN0\","
  "\"inverted\": true,\"signed\": true},\"b\": {\"channel\": \"AD2AN1\",\"inverted"
  "\": true,\"signed\": true},\"c\": {\"channel\": \"AD2AN9\",\"inverted\": true,\""
  "signed\": true},\"dcLink\": {\"channel\": \"AD1AN3\",\"inverted\": false,\"signe"
  "d\": true}},\"other\": {\"bridgeTemperature\": {\"channel\": \"AD1AN9\",\"gain\""
  ": 0.50354,\"offset\": 0.5,\"signed\": false},\"potentiometer\": {\"channel\": \""
  "AD1AN10\",\"signed\": true}},\"samplingTime\": {\"default\": 3e-07,\"maximum\": "
  "1e-06,\"minimum\": 3e-07},\"voltage\": {\"a\": {\"channel\": \"AD2AN10\",\"signe"
  "d\": false},\"b\": {\"channel\": \"AD1AN11\",\"signed\": false},\"c\": {\"channe"
  "l\": \"AD2AN7\",\"signed\": false},\"dcLink\": {\"channel\": \"AD1AN6\",\"signed"
  "\": true}}},\"comparator\": {\"inverted\": false,\"source\": \"CMP3A\",\"thresho"
  "ld\": 0.95},\"gpio\": {\"MCAF_BUTTON1\": {\"direction\": \"input\",\"pin\": \"RD"
  "9\",\"polarity\": \"active-high\"},\"MCAF_BUTTON2\": {\"direction\": \"input\","
  "\"pin\": \"RD10\",\"polarity\": \"active-high\"},\"MCAF_LED1\": {\"direction\": "
  "\"output\",\"pin\": \"RD5\",\"polarity\": \"active-high\"},\"MCAF_LED2\": {\"dir"
  "ection\": \"output\",\"pin\": \"RC9\",\"polarity\": \"active-high\"},\"MCAF_TEST"
  "POINT1\": {\"direction\": \"output\",\"pin\": \"RA1\",\"polarity\": \"active-hig"
  "h\"}},\"opamp\": {\"enabled\": [1,2,3]},\"oscillator\": {\"clockSource\": \"exte"
  "rnal clock\",\"inputClockFrequency\": 8000000},\"pwm\": {\"fault\": {\"polarity"
  "\": \"active-high\",\"source\": \"CMP3\"},\"generators\": {\"a\": 1,\"b\": 2,\"c"
  "\": 3},\"polarity\": {\"lower\": \"active-high\",\"upper\": \"active-high\"}},\""
  "qei\": {\"pins\": {\"A\": \"RC6\",\"B\": \"RC7\",\"Z\": \"RC8\"}},\"uart\": {\"p"
  "ins\": {\"RX\": \"RC11\",\"TX\": \"RC10\"}}}},\"idc\": {\"units\": \"A\"},\"samp"
  "ling_time\": {\"current\": 5e-05,\"velocity\": 0.001},\"processor\": {\"clock_fr"
  "equency\": 199687987.52,\"device\": \"dsPIC33AK128MC106\"}},\"config\": {\"ui\":"
  " {\"content\": {\"current_measure-method\": \"triple_channel\",\"current_measure"
  "-single_channel-minimumTime\": 2.0,\"current_measure-single_channel-sampleDelay"
  "\": 0.0,\"current_measure-opamp-full_input_range\": true,\"current_measure-offse"
  "t_cal-range\": 0.04,\"estimator-type\": \"zsmt\",\"estimator-active-pll\": true,"
  "\"estimator-active-smo\": false,\"estimator-active-qei\": false,\"estimator-acti"
  "ve-atpll\": false,\"estimator-active-zsmt\": false,\"estimator-active-ideal\": f"
  "alse,\"operation-min_velocity_ratio\": 0.25,\"operation-startup_velocity_ratio\""
  ": 0.2744,\"operation-max_velocity_ratio\": 1.25,\"operation-fullscale_base_ratio"
  "\": 1.5,\"operation-outer_loop_type\": \"velocity\",\"operation-saliency-thresho"
  "ld\": 1.25,\"operation-slewrate-accel\": 0.5,\"operation-slewrate-decel\": 1.0,"
  "\"operation-dyn_current_type\": \"none\",\"operation-stopping-type\": \"minimal_"
  "impact\",\"operation-stopping-closed_loop_parameters-speed\": 0.05,\"operation-s"
  "topping-closed_loop_parameters-time\": 0.5,\"operation-stopping-coastdown-end_ve"
  "locity\": 0.05,\"operation-stopping-coastdown-time\": 1.2,\"fault_inject-get_tf-"
  "div0\": false,\"fault_inject-get_tf-missing_data\": false,\"fault_inject-get_tf-"
  "raise_value_error\": false,\"fault_inject-get_tf-raise_custom_error\": false,\"f"
  "ault_inject-tf-tf_null\": false,\"fault_inject-tf-tf_jy\": false,\"fault_inject-"
  "tf-tf_jyex\": false,\"fault_inject-tf-div0\": false,\"fault_inject-tf-tau\": 0.0"
  ",\"flux_control-method\": \"none\",\"flux_control-eqn_based-ilimit-region_type\""
  ": \"quadratic\",\"flux_control-eqn_based-ilimit-id_limit\": 0.7,\"flux_control-e"
  "qn_based-ilimit-iq_limit\": 0.95,\"flux_control-eqn_based-fluxweak_enable\": fal"
  "se,\"flux_control-eqn_based-fw-vdq_limit\": 0.95,\"flux_control-eqn_based-mtpa_e"
  "nable\": false,\"deadtimecomp-method\": \"none\",\"deadtimecomp-perphase-current"
  "_sign_band\": 0.02,\"deadtimecomp-perphase-forward_gain\": 0.0,\"deadtimecomp-pe"
  "rphase-feedback_gain\": 0.0,\"fault_detect-margin_uv\": 2.0,\"fault_detect-margi"
  "n_ov\": 2.0,\"fault_detect-stall_detect_enable\": false,\"startup-Istartup\": 0."
  "75,\"startup-t_rampup\": 25.0,\"startup-t_align\": 0.0,\"startup-min_total_accel"
  "_time\": 250.0,\"startup-torque_scale_accel\": 0.15,\"startup-torque_scale_slow_"
  "accel\": 0.2,\"startup-t_hold\": 0.0,\"startup-omega0\": 0.2,\"startup-theta_con"
  "verge_rate\": 1.0,\"startup-method\": \"zsmt_dsat\",\"startup-damping-Imax\": 0."
  "133,\"startup-damping-gainmax\": 40.0,\"startup-damping-omega_min\": 0.4,\"overm"
  "odulation-vd_limit\": 1.0,\"overmodulation-vq_limit\": 1.15,\"overmodulation-inc"
  "lude_duty_clipping\": true,\"atpll-tau1\": 0.1,\"atpll-tau2\": 2.19,\"atpll-kp\""
  ": 1.9,\"atpll-ki\": 30.0,\"pll-tau\": 2.19,\"pll-omega1\": 116.5,\"pll-velocity_"
  "filter_threshold\": 1.0,\"smo-velocity_loop_cutoff\": 0.3,\"encoder-lines\": 250"
  ".0,\"encoder-index_present\": false,\"encoder-tracking_loop-tau\": 1.5,\"encoder"
  "-qei_sync-method\": \"align\",\"encoder-qei_sync-align-t_align\": 0.5,\"encoder-"
  "qei_sync-align-angle_shift\": 30.0,\"encoder-qei_sync-align-angle_init\": -30.0,"
  "\"encoder-qei_sync-align_sweep-sweep_rate_pow\": 1.0,\"encoder-qei_sync-align_sw"
  "eep-setup_angle\": 45.0,\"encoder-qei_sync-pullout-pullout_slip\": 0.117,\"zsmt-"
  "excitation-kV\": 0.12,\"zsmt-excitation-kI\": 0.1,\"zsmt-pll-zeta\": 1.5,\"zsmt-"
  "pll-tau\": 10.0,\"zsmt-pll-tau_lpf\": 0.0,\"zsmt-pll-execution_divider\": 2.0,\""
  "zsmt-startup-align_delay\": 1.0,\"zsmt-startup-pll_lock_time\": 1.0,\"zsmt-start"
  "up-speed_limit\": 0.015,\"zsmt-startup-current_limit\": 0.3,\"zsmt-startup-probe"
  "_current\": 0.3,\"zsmt-startup-probe_duration\": 10.0,\"zsmt-startup-probe_slew_"
  "time\": 1.5,\"zsmt-startup-probe_blanking_time\": 4.0,\"zsmt-hybrid-type\": \"mi"
  "notaur\",\"zsmt-minotaur-voltage_limit-vd\": 0.45,\"zsmt-minotaur-voltage_limit-"
  "vq\": 0.78,\"zsmt-minotaur-converge-angle\": 10.0,\"zsmt-minotaur-converge-durat"
  "ion\": 2.0,\"zsmt-minotaur-velocity_threshold-slow\": 0.15,\"zsmt-minotaur-veloc"
  "ity_threshold-transition\": 0.2,\"zsmt-minotaur-velocity_threshold-fast\": 0.25,"
  "\"zsmt-angle_correction-current_gain\": 0.0,\"dyn_current1-peak_factor\": 1.0,\""
  "dyn_current1-horizon_factor\": 1.05,\"dyn_current1-tau\": 5.0,\"dyn_current1-nsa"
  "mples\": 128.0,\"voltage_outerloop-tau_lpf\": 2.0,\"voltage_outerloop-Kp\": 0.1,"
  "\"voltage_outerloop-tau\": 100.0,\"mcapi-isSquaredTau\": 1.0,\"mcapi-iqTau\": 1."
  "0,\"mcapi-adcIsrUserFunctions_enable\": false,\"board_service-uiServiceTiming\":"
  " 1.0,\"board_service-uiButtonDebounceTime\": 7.0,\"board_service-uiButtonLongPre"
  "ssTime\": 2.5,\"test_harness-perturbation_asymmetric\": false,\"test_harness-cod"
  "egen-test_harness\": false,\"test_harness-codegen-test_profiling\": false,\"adc-"
  "vtempbridge\": false,\"adc-temp_bridge_params-threshold\": 50.0,\"adc-temp_bridg"
  "e_params-tau_lpf\": 10.0,\"adc-temp_bridge_params-slewrate\": 4.0,\"adc-vabsref"
  "\": false,\"adc-vphasea\": false,\"adc-vphaseb\": false,\"adc-vphasec\": false,"
  "\"diagnostics-method\": \"x2cscope\"},\"version\": {\"schema\": 6.0,\"motorBench"
  "\": \"2.55.0\",\"MCAF\": \"R9\"},\"status\": {\"valid\": true}}}}";